<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.pragmatica-lite</groupId>
        <artifactId>terra-example-apps</artifactId>
        <version>1.0.0-rc4</version>
    </parent>
    <artifactId>terra-comprehensive-persistence</artifactId>
    <properties>
        <terra.example.artifact>comprehensive-persistence</terra.example.artifact>
        <terra.example.group>org.pragmatica.aether.example</terra.example.group>
        <terra.example.version>${project.version}</terra.example.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.pragmatica-lite.aether</groupId>
            <artifactId>resource-db-async</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>${project.basedir}/../../../examples/comprehensive-persistence/src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>unchanged-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/../../../examples/comprehensive-persistence/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>application-input</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/terra-input</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/terra</directory>
                                </resource>
                                <resource>
                                    <directory>${project.basedir}/../../../examples/comprehensive-persistence/src/main/resources</directory>
                                    <includes>
                                        <include>schema/**</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.pragmatica-lite</groupId>
                <artifactId>terra-maven-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <applicationDirectory>${project.build.directory}/terra-input</applicationDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
