<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.pragmatica-lite</groupId>
        <artifactId>terra-example-apps</artifactId>
        <version>1.0.0-rc4</version>
    </parent>
    <artifactId>terra-ecommerce-fulfillment</artifactId>
    <properties>
        <terra.example.artifact>fulfillment</terra.example.artifact>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-ecommerce-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>${project.basedir}/../../../examples/ecommerce/fulfillment/src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>unchanged-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/../../../examples/ecommerce/fulfillment/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
