package org.pragmatica.jbct.slice.generator;

import org.pragmatica.jbct.slice.model.SliceModel;
import org.pragmatica.lang.Result;
import org.pragmatica.lang.Unit;
import org.pragmatica.lang.utils.Causes;

import javax.annotation.processing.Filer;
import javax.tools.StandardLocation;
import java.io.OutputStreamWriter;
import java.time.Instant;
import java.util.Properties;

public class ManifestGenerator {
    private final Filer filer;

    public ManifestGenerator(Filer filer) {
        this.filer = filer;
    }

    public Result<Unit> generate(SliceModel model) {
        try{
            var props = new Properties();
            // API artifact (with classifier)
            props.setProperty("api.artifact", getArtifactFromEnv() + ":api");
            // Slice artifact (without classifier)
            props.setProperty("slice.artifact", getArtifactFromEnv());
            // API interface fully qualified name
            props.setProperty("api.interface",
                              model.apiPackage() + "." + model.simpleName());
            // Implementation interface fully qualified name
            props.setProperty("impl.interface", model.qualifiedName());
            // Metadata
            props.setProperty("generated.timestamp",
                              Instant.now()
                                     .toString());
            props.setProperty("processor.version", getProcessorVersion());
            // Write to META-INF/slice-api.properties
            var resource = filer.createResource(StandardLocation.CLASS_OUTPUT, "", "META-INF/slice-api.properties");
            try (var writer = new OutputStreamWriter(resource.openOutputStream())) {
                props.store(writer, "Slice API manifest - generated by slice-processor");
            }
            return Result.success(Unit.unit());
        } catch (Exception e) {
            return Causes.cause("Failed to generate manifest: " + e.getMessage())
                         .result();
        }
    }

    private String getArtifactFromEnv() {
        var groupId = System.getProperty("slice.groupId", "unknown");
        var artifactId = System.getProperty("slice.artifactId", "unknown");
        return groupId + ":" + artifactId;
    }

    private String getProcessorVersion() {
        var version = getClass()
                              .getPackage()
                              .getImplementationVersion();
        return version != null
               ? version
               : "dev";
    }
}
