<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.pragmatica-lite</groupId>
        <artifactId>terra-example-apps</artifactId>
        <version>1.0.0-rc4</version>
    </parent>
    <artifactId>terra-banking-app</artifactId>
    <properties>
        <terra.example.artifact>banking-app</terra.example.artifact>
        <terra.example.group>org.pragmatica-lite.aether.example.banking</terra.example.group>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-banking-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-banking-account</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-banking-exchange</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-banking-fraud</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.pragmatica-lite</groupId>
            <artifactId>terra-banking-transfer</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>application-input</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/terra-input</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/terra</directory>
                                </resource>
                                <resource>
                                    <directory>${project.basedir}/../../../examples/banking/account/src/main/resources</directory>
                                    <includes>
                                        <include>schema/**</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.pragmatica-lite</groupId>
                <artifactId>terra-maven-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <applicationDirectory>${project.build.directory}/terra-input</applicationDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
