// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.cli.cluster.init;

import java.util.List;

import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.CloudAnswers;
import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.DatabaseAnswers;
import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.DatabaseAnswers.PasswordSource;
import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.SecretAnswers;
import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.SshAnswers;
import org.pragmatica.aether.cli.cluster.init.ClusterConfigAnswers.TlsAnswers;
import org.pragmatica.aether.config.cluster.CloudProviderName;
import org.pragmatica.aether.config.cluster.FirewallRule;
import org.pragmatica.aether.config.cluster.SourceType;


public sealed interface ClusterConfigGenerator {
    String CONFIG_VERSION = "1.0.0";
    String SOURCE_NAME = "primary";
    String IMAGE_PREFIX = "ghcr.io/pragmaticalabs/aether-node:";
    String DEFAULT_JAVA_OPTS = "-XX:+UseZGC -XX:+ZGenerational -Xms512m -Xmx2g";
    int DOCKER_CLUSTER_PORT = 6000;
    int DOCKER_SWIM_PORT = 6100;
    int DOCKER_MGMT_PORT = 8080;
    int DOCKER_APP_HTTP_PORT = 8070;

    static String generate(ClusterConfigAnswers answers) {
        var sb = new StringBuilder(2048);

        appendHeader(sb, answers);
        appendRoot(sb, answers);
        appendCluster(sb, answers);
        appendSource(sb, answers);
        appendRoles(sb, answers);
        answers.database().onPresent(db -> appendDatabase(sb, db));
        appendFirewall(sb, answers);
        appendRuntime(sb, answers);
        appendTls(sb, answers);
        appendPorts(sb, answers);
        appendAdvancedTemplates(sb);

        return sb.toString();
    }

    private static void appendHeader(StringBuilder sb, ClusterConfigAnswers answers) {
        appendComment(sb, "Generated by: aether cluster init");
        appendComment(sb, "Bootstrap with: aether cluster bootstrap cluster-config.toml");
        appendComment(sb, "");
        appendComment(sb,
                      "Cluster: " + answers.clusterName() + " (version " + answers.clusterVersion() + ")");
        appendComment(sb,
                      "Target:  " + answers.target().value());
        appendComment(sb,
                      "Topology: " + answers.topology().core() + " core + " + answers.topology().worker() + " worker");
        appendComment(sb, "");
        appendComment(sb, "Edit this file as needed; uncomment advanced sections at the bottom to enable them.");
        appendBlank(sb);
    }

    private static void appendRoot(StringBuilder sb, ClusterConfigAnswers answers) {
        appendKv(sb, "config_version", CONFIG_VERSION);
        appendKv(sb, "cluster_version", answers.clusterVersion());
        appendBlank(sb);
    }

    private static void appendCluster(StringBuilder sb, ClusterConfigAnswers answers) {
        appendSection(sb, "cluster");
        appendKv(sb, "name", answers.clusterName());
        appendKv(sb, "version", answers.clusterVersion());
        appendKv(sb, "image", IMAGE_PREFIX + answers.clusterVersion());
        appendBlank(sb);
        appendSection(sb, "cluster.core");
        appendKvBare(sb,
                     "min",
                     String.valueOf(answers.topology().core()));
        appendKvBare(sb,
                     "max",
                     String.valueOf(answers.topology().core()));
        appendKvBare(sb, "max_unavailable", "1");
        appendBlank(sb);
    }

    private static void appendSource(StringBuilder sb, ClusterConfigAnswers answers) {
        appendSection(sb, "source." + SOURCE_NAME);
        appendKv(sb,
                 "type",
                 answers.target().value());
        switch (answers.target()) {
            case CLOUD -> answers.cloud().onPresent(cloud -> appendCloudFields(sb, cloud));
            case SSH -> answers.ssh().onPresent(ssh -> appendSshFields(sb, ssh));
            case DOCKER, FORGE -> {}
        }

        appendBlank(sb);
    }

    private static void appendCloudFields(StringBuilder sb, CloudAnswers cloud) {
        appendKv(sb,
                 "provider",
                 cloud.provider().value());
        appendKv(sb, "region", cloud.region());
        appendKv(sb, "credentials", "${env:" + cloud.credentialEnvVar() + "}");
    }

    private static void appendSshFields(StringBuilder sb, SshAnswers ssh) {
        appendKv(sb, "user", ssh.user());
        appendKv(sb,
                 "key",
                 ssh.keyPath().toString());
        appendKvBare(sb,
                     "ssh_port",
                     String.valueOf(ssh.port()));
        appendKvBare(sb, "hosts", renderStringList(ssh.hosts()));
    }

    private static void appendRoles(StringBuilder sb, ClusterConfigAnswers answers) {
        appendSection(sb, "source." + SOURCE_NAME + ".core");
        appendKvBare(sb,
                     "count",
                     String.valueOf(answers.topology().core()));
        answers.cloud().onPresent(cloud -> appendKv(sb, "instance_type", cloud.instanceType()));
        appendBlank(sb);
        if (answers.topology().worker() > 0) {
            appendSection(sb, "source." + SOURCE_NAME + ".worker");
            appendKvBare(sb,
                         "count",
                         String.valueOf(answers.topology().worker()));
            answers.cloud().onPresent(cloud -> appendKv(sb, "instance_type", cloud.instanceType()));
            appendBlank(sb);
        }
    }

    private static void appendDatabase(StringBuilder sb, DatabaseAnswers db) {
        appendSection(sb, "source." + SOURCE_NAME + ".databases.primary");
        appendKv(sb, "database_host", db.host());
        appendKvBare(sb,
                     "database_port",
                     String.valueOf(db.port()));
        appendKv(sb, "database_name", db.name());
        appendKv(sb, "database_username", db.user());
        appendKv(sb, "database_password", renderPassword(db.password()));
        appendBlank(sb);
    }

    private static String renderPassword(PasswordSource password) {
        return switch (password) {
            case PasswordSource.FromEnv fromEnv -> "${env:" + fromEnv.envVar() + "}";
            case PasswordSource.Plaintext plaintext -> plaintext.value();
        };
    }

    private static void appendFirewall(StringBuilder sb, ClusterConfigAnswers answers) {
        if (skipFirewall(answers)) {
            return;
        }

        var rules = effectiveFirewallRules(answers);

        if (rules.isEmpty()) {
            return;
        }

        for (var rule : rules) {
            appendArrayOfTablesHeader(sb, "source." + SOURCE_NAME + ".firewall.allow_ingress");
            appendKvBare(sb,
                         "port",
                         String.valueOf(rule.port()));
            appendKv(sb, "protocol", rule.protocol());
            appendKv(sb, "source_cidr", rule.sourceCidr());
            rule.description().onPresent(desc -> appendKv(sb, "description", desc));
            appendBlank(sb);
        }
    }

    /// Scaffold `allow_ingress` ONLY where Aether actually applies it — a generated config that
    /// pre-flight then rejects (PF-23), or that is silently inert, is worse than no block at all.
    ///
    /// - Docker/Forge: no cloud API, nothing to manage.
    /// - SSH: the host's firewall is the operator's; Aether never touches it.
    /// - Cloud on AWS/GCP/Azure: ingress arms are not implemented, and PF-23 rejects the block.
    ///   Their defaults deny inbound, so omitting it exposes nothing.
    /// - `OPEN` preset: the operator asked for no rules.
    private static boolean skipFirewall(ClusterConfigAnswers answers) {
        var target = answers.target();

        if (target != SourceType.CLOUD) {
            return true;
        }

        if (answers.firewallPreset() == FirewallPreset.OPEN) {
            return true;
        }

        return ! answers.cloud()
                        .map(cloud -> cloud.provider() == CloudProviderName.HETZNER)
                        .or(false);
    }

    private static List<FirewallRule> effectiveFirewallRules(ClusterConfigAnswers answers) {
        if (answers.firewallPreset() == FirewallPreset.CUSTOM) {
            return answers.customFirewallRules();
        }

        var adminCidr = answers.adminCidr().or(FirewallPresets.ANY_CIDR);
        var internalCidr = answers.internalCidr().or(FirewallPresets.DEFAULT_INTERNAL_CIDR);

        return FirewallPresets.rulesFor(answers.firewallPreset(), adminCidr, internalCidr);
    }

    private static void appendRuntime(StringBuilder sb, ClusterConfigAnswers answers) {
        appendSection(sb, "runtime.default");
        appendKv(sb, "type", runtimeTypeFor(answers.target()));
        appendKv(sb, "image", IMAGE_PREFIX + answers.clusterVersion());
        appendKv(sb, "jvm_args", DEFAULT_JAVA_OPTS);
        appendComment(sb, "Per-runtime environment variables (uncomment to set):");
        appendComment(sb, "[runtime.default.env]");
        appendComment(sb, "JAVA_TOOL_OPTIONS = \"-Dfile.encoding=UTF-8\"");
        appendComment(sb, "AETHER_LOG_LEVEL = \"INFO\"");
        appendBlank(sb);
    }

    private static String runtimeTypeFor(SourceType target) {
        return switch (target) {
            case DOCKER -> "docker";
            case FORGE -> "ember";
            case CLOUD, SSH -> "container";
        };
    }

    private static void appendTls(StringBuilder sb, ClusterConfigAnswers answers) {
        if (answers.target() == SourceType.DOCKER || answers.target() == SourceType.FORGE || answers.tls() instanceof TlsAnswers.Skipped) {
            appendCommentedTlsTemplate(sb);

            return;
        }

        appendSection(sb, "operations.tls");
        switch (answers.tls()) {
            case TlsAnswers.AutoGenerate _ -> appendKvBare(sb, "auto_generate", "true");
            case TlsAnswers.Manual manual -> appendManualTls(sb, manual);
            case TlsAnswers.Skipped _ -> {}
        }

        appendSecret(sb, answers.secret());
        appendBlank(sb);
    }

    private static void appendCommentedTlsTemplate(StringBuilder sb) {
        appendComment(sb, "TLS (uncomment to enable for production / non-local clusters):");
        appendComment(sb, "[operations.tls]");
        appendComment(sb, "auto_generate = true");
        appendComment(sb, "cluster_secret = \"${env:AETHER_CLUSTER_SECRET}\"");
        appendBlank(sb);
    }

    private static void appendManualTls(StringBuilder sb, TlsAnswers.Manual manual) {
        appendKvBare(sb, "auto_generate", "false");
        appendKv(sb, "cert_path", "${env:" + manual.certPathEnvVar() + "}");
        appendKv(sb, "key_path", "${env:" + manual.keyPathEnvVar() + "}");
    }

    private static void appendSecret(StringBuilder sb, SecretAnswers secret) {
        switch (secret) {
            case SecretAnswers.AutoGenerate _ -> {}
            case SecretAnswers.FromEnv fromEnv -> appendKv(sb, "cluster_secret", "${env:" + fromEnv.envVar() + "}");
            case SecretAnswers.Skipped _ -> {}
        }
    }

    private static void appendPorts(StringBuilder sb, ClusterConfigAnswers answers) {
        appendSection(sb, "operations.ports");
        var docker = answers.target() == SourceType.DOCKER;

        appendKvBare(sb,
                     "cluster",
                     String.valueOf(docker
                                    ? DOCKER_CLUSTER_PORT
                                    : FirewallPresets.CLUSTER_PORT));
        appendKvBare(sb,
                     "management",
                     String.valueOf(docker
                                    ? DOCKER_MGMT_PORT
                                    : FirewallPresets.MGMT_PORT));
        appendKvBare(sb,
                     "app_http",
                     String.valueOf(docker
                                    ? DOCKER_APP_HTTP_PORT
                                    : FirewallPresets.APP_HTTP_PORT));
        appendKvBare(sb,
                     "swim",
                     String.valueOf(docker
                                    ? DOCKER_SWIM_PORT
                                    : FirewallPresets.SWIM_PORT));
        appendBlank(sb);
    }

    private static void appendAdvancedTemplates(StringBuilder sb) {
        appendComment(sb, "------------------------------------------------------------");
        appendComment(sb, "Advanced configuration (uncomment as needed):");
        appendComment(sb, "------------------------------------------------------------");
        appendComment(sb, "");
        appendComment(sb, "[operations.auto_heal]");
        appendComment(sb, "enabled = true");
        appendComment(sb, "retry_interval = \"60s\"");
        appendComment(sb, "startup_cooldown = \"15s\"");
        appendComment(sb, "");
        appendComment(sb, "[operations.timeouts]");
        appendComment(sb, "health_check = \"300s\"");
        appendComment(sb, "quorum_formation = \"600s\"");
        appendComment(sb, "drain = \"120s\"");
        appendComment(sb, "");
        appendComment(sb, "Per-source node-config overrides (composed onto every node from this source):");
        appendComment(sb, "[source." + SOURCE_NAME + ".node_config.logging]");
        appendComment(sb, "level = \"INFO\"");
        appendComment(sb, "");
        appendComment(sb, "[source." + SOURCE_NAME + ".node_config.app-http]");
        appendComment(sb, "timeout = \"30s\"");
    }

    private static void appendBlank(StringBuilder sb) {
        sb.append('\n');
    }

    private static void appendComment(StringBuilder sb, String comment) {
        if (comment.isEmpty()) {
            sb.append("#\n");

            return;
        }

        sb.append("# ").append(comment).append('\n');
    }

    private static void appendSection(StringBuilder sb, String name) {
        sb.append('[').append(name).append("]\n");
    }

    private static void appendArrayOfTablesHeader(StringBuilder sb, String name) {
        sb.append("[[").append(name).append("]]\n");
    }

    private static void appendKv(StringBuilder sb, String key, String value) {
        sb.append(key).append(" = \"").append(escapeString(value)).append("\"\n");
    }

    private static void appendKvBare(StringBuilder sb, String key, String rawValue) {
        sb.append(key).append(" = ").append(rawValue).append('\n');
    }

    private static String escapeString(String value) {
        var sb = new StringBuilder(value.length() + 4);

        for (int i = 0; i < value.length(); i++) {
            var ch = value.charAt(i);

            switch (ch) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(ch);
            }
        }

        return sb.toString();
    }

    private static String renderStringList(List<String> values) {
        var sb = new StringBuilder("[");

        for (int i = 0; i < values.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }

            sb.append('"').append(escapeString(values.get(i))).append('"');
        }

        return sb.append(']')
                 .toString();
    }

    record unused() implements ClusterConfigGenerator {}
}
