// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.cli.cluster.init;

import org.pragmatica.lang.Cause;


public sealed interface ClusterInitError extends Cause {
    record TooFewNodes(int got) implements ClusterInitError {
        @Override
        public String message() {
            return "Aether requires at least 3 nodes for consensus quorum (got " + got
                 + "). "
                 + "For local single-process dev/test, use --target forge.";
        }
    }

    record InvalidTopology(String detail) implements ClusterInitError {
        @Override
        public String message() {
            return "Invalid topology: " + detail;
        }
    }

    record OutputExists(String path) implements ClusterInitError {
        @Override
        public String message() {
            return "Output file already exists: " + path + ". Re-run with --force to overwrite.";
        }
    }

    record MissingField(String name) implements ClusterInitError {
        @Override
        public String message() {
            return "Required field missing or invalid: " + name;
        }
    }

    /// A cloud target reached config generation with no instance type, and there is deliberately
    /// NO default to fall back on.
    ///
    /// Cloud providers RETIRE instance types. `ClusterConfigWizard.defaultInstanceFor` used to
    /// answer this with `cx21` (Hetzner), `t3.medium` (AWS), `e2-medium` (GCP) and `Standard_B2s`
    /// (Azure); Hetzner has since deleted `cx21` from its catalogue, so a config generated by
    /// pressing Enter through the wizard could not provision in ANY region — three consecutive
    /// `aether cluster bootstrap` runs on 2026-09-10 died on
    /// `422 (invalid_input): unsupported location for server type`, in two different regions.
    ///
    /// A baked-in default is a snapshot of someone else's catalogue and rots with no signal on
    /// this side, so the operator is required to supply the value. The message names the flag and
    /// the provider because the catalogue that has to be consulted is the provider's, not ours.
    record InstanceTypeRequired(String provider) implements ClusterInitError {
        @Override
        public String message() {
            return "No instance type given for cloud provider '" + provider
                 + "', and Aether ships no default on purpose: supply --instance-type. "
                 + "Providers retire instance types and vary availability by location, so the value "
                 + "must come from " + provider
                 + "'s CURRENT catalogue for the chosen region.";
        }
    }

    record InvalidValue(String field, String got, String expected) implements ClusterInitError {
        @Override
        public String message() {
            return "Invalid " + field + " '" + got + "': " + expected;
        }
    }

    enum Aborted implements ClusterInitError {
        INSTANCE;
        @Override
        public String message() {
            return "Wizard aborted by operator.";
        }
    }

    record ConfigValidationFailed(String detail) implements ClusterInitError {
        @Override
        public String message() {
            return "Generated configuration failed validation: " + detail;
        }
    }

    record IoFailure(String path, String reason) implements ClusterInitError {
        @Override
        public String message() {
            return "Failed to write " + path + ": " + reason;
        }
    }
}
