package org.pragmatica.aether.pg.parser.grammar;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class DdlTest extends GrammarTestBase {

    @Nested
    class CreateTable {
        @Test void minimal() {
            assertParses("CREATE TABLE test (id integer)");
        }

        @Test void ifNotExists() {
            assertParses("CREATE TABLE IF NOT EXISTS test (id integer)");
        }

        @Test void schemaQualified() {
            assertParses("CREATE TABLE public.users (id integer)");
        }

        @Test void multipleColumns() {
            assertParses("CREATE TABLE users (id bigint NOT NULL, name text, email varchar(255) NOT NULL)");
        }

        @Test void withDefaults() {
            assertParses("CREATE TABLE users (id bigserial, created_at timestamptz DEFAULT now() NOT NULL)");
        }

        @Test void inlinePrimaryKey() {
            assertParses("CREATE TABLE users (id bigint PRIMARY KEY, name text NOT NULL)");
        }

        @Test void tablePrimaryKey() {
            assertParses("CREATE TABLE users (id bigint NOT NULL, name text, PRIMARY KEY (id))");
        }

        @Test void compositePrimaryKey() {
            assertParses("CREATE TABLE film_actor (actor_id integer NOT NULL, film_id integer NOT NULL, PRIMARY KEY (actor_id, film_id))");
        }

        @Test void foreignKey() {
            assertParses("CREATE TABLE orders (id bigint PRIMARY KEY, user_id bigint REFERENCES users(id))");
        }

        @Test void tableForeignKey() {
            assertParses("CREATE TABLE orders (id bigint, user_id bigint, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT)");
        }

        @Test void uniqueConstraint() {
            assertParses("CREATE TABLE users (id bigint, email text, CONSTRAINT uq_email UNIQUE (email))");
        }

        @Test void checkConstraint() {
            assertParses("CREATE TABLE products (id bigint, price numeric(10,2), CHECK (price > 0))");
        }

        @Test void namedConstraints() {
            assertParses("CREATE TABLE test (id bigint, CONSTRAINT pk_test PRIMARY KEY (id), CONSTRAINT chk_id CHECK (id > 0))");
        }

        @Test void generatedAlwaysStored() {
            assertParses("CREATE TABLE test (a integer, b integer, sum_ab integer GENERATED ALWAYS AS (a + b) STORED)");
        }

        @Test void identityColumn() {
            assertParses("CREATE TABLE test (id integer GENERATED ALWAYS AS IDENTITY)");
        }

        @Test void identityByDefault() {
            assertParses("CREATE TABLE test (id integer GENERATED BY DEFAULT AS IDENTITY)");
        }

        @Test void arrayColumn() {
            assertParses("CREATE TABLE test (id integer, tags text[], scores integer[])");
        }

        @Test void jsonbColumn() {
            assertParses("CREATE TABLE test (id integer, metadata jsonb DEFAULT '{}' NOT NULL)");
        }

        @Test void timestampWithTimezone() {
            assertParses("CREATE TABLE test (id integer, created_at timestamp with time zone NOT NULL)");
        }

        @Test void numericPrecision() {
            assertParses("CREATE TABLE test (id integer, amount numeric(10,2) DEFAULT 0.00 NOT NULL)");
        }

        @Test void serialTypes() {
            assertParses("CREATE TABLE test (id bigserial NOT NULL, code serial)");
        }

        @Test void partitionByRange() {
            assertParses("CREATE TABLE payment (id integer, amount numeric(5,2), payment_date timestamptz, PRIMARY KEY (payment_date, id)) PARTITION BY RANGE (payment_date)");
        }

        @Test void partitionByList() {
            assertParses("CREATE TABLE measurement (city_id integer, logdate date) PARTITION BY LIST (city_id)");
        }

        @Test void partitionByHash() {
            assertParses("CREATE TABLE test (id integer) PARTITION BY HASH (id)");
        }

        @Test void tempTable() {
            assertParses("CREATE TEMP TABLE tmp_data (id integer, val text)");
        }

        @Test void unloggedTable() {
            assertParses("CREATE UNLOGGED TABLE fast_data (id integer, val text)");
        }

        @Test void collate() {
            assertParses("CREATE TABLE test (id integer, name text COLLATE \"en_US\")");
        }

        @Test void multipleDefaults() {
            assertParses("CREATE TABLE categories (id integer NOT NULL, color varchar(6) DEFAULT 'AB9364' NOT NULL, topic_count integer DEFAULT 0 NOT NULL)");
        }

        @Test void complexRealWorld() {
            assertParses("""
                CREATE TABLE public.film (
                    film_id integer DEFAULT nextval('film_film_id_seq') NOT NULL,
                    title text NOT NULL,
                    description text,
                    release_year integer,
                    language_id integer NOT NULL,
                    rental_duration smallint DEFAULT 3 NOT NULL,
                    rental_rate numeric(4,2) DEFAULT 4.99 NOT NULL,
                    length smallint,
                    replacement_cost numeric(5,2) DEFAULT 19.99 NOT NULL,
                    last_update timestamp with time zone DEFAULT now() NOT NULL,
                    special_features text[],
                    fulltext tsvector NOT NULL
                )""");
        }
    }

    @Nested
    class AlterTable {
        @Test void addColumn() {
            assertParses("ALTER TABLE users ADD COLUMN phone varchar(20)");
        }

        @Test void addColumnIfNotExists() {
            assertParses("ALTER TABLE users ADD COLUMN IF NOT EXISTS phone varchar(20)");
        }

        @Test void dropColumn() {
            assertParses("ALTER TABLE users DROP COLUMN legacy_id");
        }

        @Test void dropColumnIfExists() {
            assertParses("ALTER TABLE users DROP COLUMN IF EXISTS legacy_id CASCADE");
        }

        @Test void renameColumn() {
            assertParses("ALTER TABLE users RENAME COLUMN name TO display_name");
        }

        @Test void renameTable() {
            assertParses("ALTER TABLE users RENAME TO accounts");
        }

        @Test void alterColumnType() {
            assertParses("ALTER TABLE users ALTER COLUMN email TYPE varchar(320)");
        }

        @Test void setDefault() {
            assertParses("ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now()");
        }

        @Test void dropDefault() {
            assertParses("ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT");
        }

        @Test void setNotNull() {
            assertParses("ALTER TABLE users ALTER COLUMN display_name SET NOT NULL");
        }

        @Test void dropNotNull() {
            assertParses("ALTER TABLE users ALTER COLUMN phone DROP NOT NULL");
        }

        @Test void addConstraintUnique() {
            assertParses("ALTER TABLE users ADD CONSTRAINT uq_email UNIQUE (email)");
        }

        @Test void addConstraintCheck() {
            assertParses("ALTER TABLE users ADD CONSTRAINT chk_email CHECK (email LIKE '%@%')");
        }

        @Test void addConstraintForeignKey() {
            assertParses("ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE");
        }

        @Test void addConstraintNotValid() {
            assertParses("ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) NOT VALID");
        }

        @Test void dropConstraint() {
            assertParses("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_email CASCADE");
        }

        @Test void validateConstraint() {
            assertParses("ALTER TABLE orders VALIDATE CONSTRAINT fk_user");
        }

        @Test void addPrimaryKey() {
            assertParses("ALTER TABLE ONLY public.actor ADD CONSTRAINT actor_pkey PRIMARY KEY (actor_id)");
        }

        @Test void setSchema() {
            assertParses("ALTER TABLE users SET SCHEMA archive");
        }

        @Test void attachPartition() {
            assertParses("ALTER TABLE ONLY public.payment ATTACH PARTITION public.payment_p2022_01 FOR VALUES FROM ('2022-01-01') TO ('2022-02-01')");
        }

        @Test void detachPartition() {
            assertParses("ALTER TABLE measurement DETACH PARTITION measurement_y2024");
        }

        @Test void multipleActions() {
            assertParses("ALTER TABLE orders ADD COLUMN shipping_address_id integer, ADD COLUMN discount_pct numeric(5,2) DEFAULT 0, ALTER COLUMN total SET NOT NULL");
        }
    }

    @Nested
    class DropTable {
        @Test void simple() { assertParses("DROP TABLE users"); }
        @Test void ifExists() { assertParses("DROP TABLE IF EXISTS users"); }
        @Test void cascade() { assertParses("DROP TABLE IF EXISTS old_data CASCADE"); }
        @Test void multiple() { assertParses("DROP TABLE t1, t2, t3 CASCADE"); }
    }

    @Nested
    class CreateIndex {
        @Test void simple() {
            assertParses("CREATE INDEX idx_name ON users (name)");
        }

        @Test void unique() {
            assertParses("CREATE UNIQUE INDEX idx_email ON users (email)");
        }

        @Test void concurrently() {
            assertParses("CREATE INDEX CONCURRENTLY idx_name ON users (name)");
        }

        @Test void ifNotExists() {
            assertParses("CREATE INDEX IF NOT EXISTS idx_name ON users (name)");
        }

        @Test void btree() {
            assertParses("CREATE INDEX idx_name ON users USING btree (name)");
        }

        @Test void gin() {
            assertParses("CREATE INDEX idx_attrs ON products USING gin (attributes)");
        }

        @Test void gist() {
            assertParses("CREATE INDEX idx_fulltext ON film USING gist (fulltext)");
        }

        @Test void composite() {
            assertParses("CREATE INDEX idx_store_film ON inventory (store_id, film_id)");
        }

        @Test void partial() {
            assertParses("CREATE INDEX idx_active ON products (name) WHERE deleted_at IS NULL");
        }

        @Test void partialComplex() {
            assertParses("CREATE UNIQUE INDEX idx_unique_actions ON post_actions (user_id, post_action_type_id, post_id) WHERE deleted_at IS NULL AND disagreed_at IS NULL");
        }

        @Test void expressionIndex() {
            assertParses("CREATE INDEX idx_lower_name ON products (lower(name))");
        }

        @Test void jsonbExpressionIndex() {
            assertParses("CREATE INDEX idx_sku ON products ((attributes->>'sku'))");
        }

        @Test void includeClause() {
            assertParses("CREATE INDEX idx_covering ON orders (customer_id) INCLUDE (total, status)");
        }

        @Test void withStorageParams() {
            assertParses("CREATE INDEX idx_gin ON products USING gin (attributes) WITH (fastupdate = 1)");
        }

        @Test void descNullsFirst() {
            assertParses("CREATE INDEX idx_recent ON events (created_at DESC NULLS FIRST)");
        }
    }

    @Nested
    class DropIndex {
        @Test void simple() { assertParses("DROP INDEX idx_name"); }
        @Test void concurrently() { assertParses("DROP INDEX CONCURRENTLY IF EXISTS idx_name"); }
    }

    @Nested
    class Sequence {
        @Test void create() {
            assertParses("CREATE SEQUENCE user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1");
        }

        @Test void alter() {
            assertParses("ALTER SEQUENCE user_id_seq RESTART START WITH 100");
        }

        @Test void drop() {
            assertParses("DROP SEQUENCE IF EXISTS user_id_seq");
        }
    }

    @Nested
    class TypeDdl {
        @Test void createEnum() {
            assertParses("CREATE TYPE public.order_status AS ENUM ('pending', 'processing', 'shipped', 'delivered')");
        }

        @Test void alterTypeAddValue() {
            assertParses("ALTER TYPE public.order_status ADD VALUE 'refunded' AFTER 'delivered'");
        }

        @Test void alterTypeAddValueIfNotExists() {
            assertParses("ALTER TYPE public.order_status ADD VALUE IF NOT EXISTS 'on_hold' BEFORE 'shipped'");
        }

        @Test void createComposite() {
            assertParses("CREATE TYPE address AS (street text, city text, zip varchar(10))");
        }

        @Test void createDomain() {
            assertParses("CREATE TYPE public.year AS integer CONSTRAINT year_check CHECK (VALUE >= 1901 AND VALUE <= 2155)");
        }

        @Test void drop() {
            assertParses("DROP TYPE IF EXISTS order_status CASCADE");
        }
    }

    @Nested
    class SchemaDdl {
        @Test void create() { assertParses("CREATE SCHEMA myschema"); }
        @Test void createIfNotExists() { assertParses("CREATE SCHEMA IF NOT EXISTS myschema"); }
        @Test void createWithAuth() { assertParses("CREATE SCHEMA myschema AUTHORIZATION admin"); }
        @Test void drop() { assertParses("DROP SCHEMA IF EXISTS myschema CASCADE"); }
    }

    @Nested
    class ViewDdl {
        @Test void createView() {
            assertParses("CREATE VIEW active_users AS SELECT id, name FROM users WHERE active = true");
        }

        @Test void createOrReplace() {
            assertParses("CREATE OR REPLACE VIEW active_users AS SELECT id, name FROM users WHERE active = true");
        }

        @Test void createMaterializedView() {
            assertParses("CREATE MATERIALIZED VIEW IF NOT EXISTS user_stats AS SELECT count(*) FROM users");
        }

        @Test void dropView() { assertParses("DROP VIEW IF EXISTS active_users CASCADE"); }
        @Test void dropMatView() { assertParses("DROP MATERIALIZED VIEW IF EXISTS user_stats"); }
    }

    @Nested
    class ExtensionDdl {
        @Test void create() { assertParses("CREATE EXTENSION IF NOT EXISTS hstore"); }
        @Test void createWithSchema() { assertParses("CREATE EXTENSION pg_trgm WITH SCHEMA public"); }
        @Test void drop() { assertParses("DROP EXTENSION IF EXISTS hstore CASCADE"); }
    }

    @Nested
    class CommentDdl {
        @Test void onTable() { assertParses("COMMENT ON TABLE users IS 'User accounts'"); }
        @Test void onColumn() { assertParses("COMMENT ON COLUMN users.email IS 'Primary email'"); }
        @Test void removeComment() { assertParses("COMMENT ON TABLE users IS NULL"); }
    }

    @Nested
    class GrantRevoke {
        @Test void grantSelect() { assertParses("GRANT SELECT ON users TO readonly"); }
        @Test void grantAll() { assertParses("GRANT ALL PRIVILEGES ON TABLE users TO admin"); }
        @Test void grantOnSchema() { assertParses("GRANT USAGE ON SCHEMA public TO app_user"); }
        @Test void revoke() { assertParses("REVOKE INSERT, UPDATE ON users FROM readonly"); }
    }
}
