package org.pragmatica.jbct.parser.v6;

import org.pragmatica.peg.cst.CstArray;
import org.pragmatica.peg.cst.ParseResult;
import org.pragmatica.peg.token.TokenArray;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/// Stage 0 of the v6 migration plan: probe the v6 CST shape for the B1-B4 fixtures and
/// dump findings to `jbct/docs/v6-cst-shape-probe.md`. Read by the migration plan to
/// decide formatter dispatch design ahead of Stage 4.
public final class CstShapeProbe {
    private static final Path FIXTURES = resolveBase().resolve("jbct-format/src/test/resources/format-examples");
    private static final Path REPORT = resolveBase().resolve("docs/v6-cst-shape-probe.md");

    private static Path resolveBase() {
        // Probe may run from reactor root, jbct/ root, or jbct-parser. Walk up until we find jbct/jbct-format.
        var p = Path.of("").toAbsolutePath();
        for (int i = 0; i < 4; i++) {
            if (Files.isDirectory(p.resolve("jbct/jbct-format"))) {
                return p.resolve("jbct");
            }
            if (Files.isDirectory(p.resolve("jbct-format"))) {
                return p;
            }
            p = p.getParent();
            if (p == null) break;
        }
        throw new IllegalStateException("Could not locate jbct/jbct-format from cwd");
    }
    private static final int MAX_DEPTH = 9;
    private static final int TRIVIA_BUDGET = 200;

    public static void main(String[] args) throws IOException {
        var sb = new StringBuilder();
        header(sb);

        for (String fixture : new String[]{
            "CommentsExtended.java",
            "ChainAlignment.java",
            "KeywordPrefixedIdentifiers.java",
            "Lambdas.java",
            "SwitchExpressions.java"
        }) {
            probeFile(sb, FIXTURES.resolve(fixture), fixture);
        }
        probeSynthetic(sb,
            "Multi-statement if-body (synthetic)",
            "class X { void m() { if (a > 0) { System.out.println(); var y = 1; } } }");

        Files.writeString(REPORT, sb.toString());
        System.out.println("Wrote " + REPORT.toAbsolutePath().normalize() + " (" + sb.length() + " chars)");
    }

    private static void header(StringBuilder sb) {
        sb.append("# v6 CST shape probe (Stage 0 of migration plan)\n\n");
        sb.append("**Generated by:** `org.pragmatica.jbct.parser.v6.CstShapeProbe`\n");
        sb.append("**Purpose:** ground-truth CST shape per fixture under v6 emit before Stage 1.\n");
        sb.append("**Methodology:** for each fixture, parse via Java25Lexer.lex + Java25ParserV6.parse, then dump:\n");
        sb.append("- Token kind histogram (kind → count)\n");
        sb.append("- CST tree up to depth ").append(MAX_DEPTH).append("\n");
        sb.append("- Per-node leading-trivia-token count for the first 3 ClassMember / BlockStmt descendants\n\n");
        sb.append("---\n\n");
    }

    private static void probeFile(StringBuilder sb, Path path, String name) throws IOException {
        var src = Files.readString(path);
        section(sb, name, src);
    }

    private static void probeSynthetic(StringBuilder sb, String name, String src) {
        section(sb, name, src);
    }

    private static void section(StringBuilder sb, String name, String src) {
        sb.append("## ").append(name).append("\n\n");

        var tokens = Java25Lexer.lex(src);
        var pr = Java25ParserV6.parse(tokens);
        var cst = pr.cst();

        sb.append("**Source length:** ").append(src.length()).append(" chars  \n");
        sb.append("**Token count:** ").append(tokens.count()).append("  \n");
        sb.append("**CST node count:** ").append(cst.nodeCount()).append("  \n");
        sb.append("**Parse success:** ").append(pr.isSuccess()).append("  \n");
        sb.append("**Has errors:** ").append(pr.hasErrors()).append("  \n\n");

        sb.append("### Token kind histogram\n\n```\n");
        sb.append(tokenHistogram(tokens, cst.ruleTable())).append("\n```\n\n");

        sb.append("### CST shape (depth ≤ ").append(MAX_DEPTH).append(")\n\n```\n");
        dumpNode(sb, cst, cst.rootIndex(), 0, MAX_DEPTH);
        sb.append("```\n\n");

        sb.append("### Per-node leading-trivia-token summary\n\n");
        dumpTriviaSummary(sb, cst, cst.rootIndex(), TRIVIA_BUDGET);

        sb.append("\n### Brace-body Stmt shape audit\n\n");
        sb.append("Probe target: does v6 produce `Stmt[T<{>, BlockStmt*, T<}>]` (clean) or `Stmt[T<{>, Block[BlockStmt*], T<}>]` (legacy-style wrapping) for if/for/while bodies?\n\n");
        dumpStmtBraceShapes(sb, cst, cst.rootIndex(), 0);

        sb.append("\n---\n\n");
    }

    private static String tokenHistogram(TokenArray tokens, String[] ruleTable) {
        var hist = new LinkedHashMap<Integer, Integer>();
        for (int i = 0; i < tokens.count(); i++) {
            int k = tokens.kindAt(i);
            hist.merge(k, 1, Integer::sum);
        }
        var sb = new StringBuilder();
        hist.forEach((kindId, count) -> {
            String name = kindId < Java25Lexer.KIND_NAMES.length ? Java25Lexer.KIND_NAMES[kindId] : "<unknown>";
            sb.append(String.format("  kind=%3d (%s) count=%d%n", kindId, name, count));
        });
        return sb.toString();
    }

    private static void dumpNode(StringBuilder sb, CstArray cst, int idx, int depth, int maxDepth) {
        if (depth > maxDepth) {
            return;
        }
        if (idx == CstArray.NO_NODE) {
            return;
        }
        var ind = "  ".repeat(depth);
        var name = cst.kindNameAt(idx);
        int firstTok = cst.firstTokenAt(idx);
        int lastTok = cst.lastTokenAt(idx);
        int firstChild = cst.firstChildAt(idx);
        boolean isLeaf = firstChild == CstArray.NO_NODE;
        int triviaCount = (int) cst.leadingTriviaTokens(idx).count();
        sb.append(String.format(
            "%s%s [span=%d-%d, tokens=%d..%d, leaf=%s, leadingTrivia=%d]",
            ind, name, cst.spanStart(idx), cst.spanEnd(idx), firstTok, lastTok, isLeaf, triviaCount));
        if (isLeaf) {
            var text = cst.textAt(idx).toString();
            if (text.length() > 30) {
                text = text.substring(0, 27) + "...";
            }
            sb.append(" text=\"").append(escape(text)).append("\"");
        }
        sb.append("\n");
        if (depth == maxDepth) {
            int childCount = 0;
            for (int c = firstChild; c != CstArray.NO_NODE; c = cst.nextSiblingAt(c)) {
                childCount++;
            }
            if (childCount > 0) {
                sb.append("  ".repeat(depth + 1)).append("... (").append(childCount).append(" children truncated)\n");
            }
            return;
        }
        for (int c = firstChild; c != CstArray.NO_NODE; c = cst.nextSiblingAt(c)) {
            dumpNode(sb, cst, c, depth + 1, maxDepth);
        }
    }

    private static int dumpTriviaSummary(StringBuilder sb, CstArray cst, int idx, int budget) {
        if (idx == CstArray.NO_NODE || budget <= 0) {
            return budget;
        }
        var ruleName = cst.kindNameAt(idx);
        boolean relevantKind = "ClassMember".equals(ruleName)
            || "Member".equals(ruleName)
            || "FieldDecl".equals(ruleName)
            || "MethodDecl".equals(ruleName)
            || "BlockStmt".equals(ruleName);
        if (relevantKind) {
            int count = (int) cst.leadingTriviaTokens(idx).count();
            if (count > 0) {
                var tokenSummary = new StringBuilder();
                cst.leadingTriviaTokens(idx).limit(8).forEach(tokIdx -> {
                    int kind = cst.tokens().kindAt(tokIdx);
                    var kindName = kind < Java25Lexer.KIND_NAMES.length
                        ? Java25Lexer.KIND_NAMES[kind]
                        : "<unknown>";
                    var text = cst.tokens().textAt(tokIdx).toString();
                    if (text.length() > 20) {
                        text = text.substring(0, 17) + "...";
                    }
                    tokenSummary.append(String.format("[%s:%s]", kindName, escape(text)));
                });
                sb.append(String.format(
                    "- %s @ span=%d-%d leadingTrivia=%d %s%n",
                    ruleName, cst.spanStart(idx), cst.spanEnd(idx), count, tokenSummary));
                budget--;
            }
        }
        for (int c = cst.firstChildAt(idx); c != CstArray.NO_NODE && budget > 0; c = cst.nextSiblingAt(c)) {
            budget = dumpTriviaSummary(sb, cst, c, budget);
        }
        return budget;
    }

    private static void dumpStmtBraceShapes(StringBuilder sb, CstArray cst, int idx, int depth) {
        if (idx == CstArray.NO_NODE) {
            return;
        }
        var ruleName = cst.kindNameAt(idx);
        if ("Stmt".equals(ruleName)) {
            // Examine children layout
            var childRules = new StringBuilder("[");
            int childCount = 0;
            for (int c = cst.firstChildAt(idx); c != CstArray.NO_NODE; c = cst.nextSiblingAt(c)) {
                if (childCount > 0) childRules.append(", ");
                childRules.append(cst.kindNameAt(c));
                if (childCount < 5) {
                    int tokFirst = cst.firstTokenAt(c);
                    int tokKind = tokFirst >= 0 ? cst.tokens().kindAt(tokFirst) : -1;
                    if (tokKind == 92 /* INLINE__LBRACE */ || tokKind == 93 /* INLINE__RBRACE */) {
                        childRules.append("(").append(tokKind == 92 ? "{" : "}").append(")");
                    }
                }
                childCount++;
            }
            childRules.append("]");
            if (childCount > 0) {
                int firstChild = cst.firstChildAt(idx);
                int firstChildFirstTok = firstChild >= 0 ? cst.firstTokenAt(firstChild) : -1;
                int firstChildKind = firstChildFirstTok >= 0 ? cst.tokens().kindAt(firstChildFirstTok) : -1;
                boolean braceShaped = firstChildKind == 92; // INLINE__LBRACE
                sb.append(String.format(
                    "- Stmt @ span=%d-%d children=%d braceShaped=%s shape=%s%n",
                    cst.spanStart(idx), cst.spanEnd(idx), childCount, braceShaped, childRules));
            }
        }
        for (int c = cst.firstChildAt(idx); c != CstArray.NO_NODE; c = cst.nextSiblingAt(c)) {
            dumpStmtBraceShapes(sb, cst, c, depth + 1);
        }
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r");
    }
}
