// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.

package com.example.hostslice;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

/// Permanent regression gate for the codec-generation shadowing bug (PR #364, part 2), realized as a
/// slice-injects-slice fixture: [BookingSlice] injects [com.example.injectedslice.QuoteSlice] and BOTH
/// declare nested `Request`/`Response`.
///
/// The generated `BookingSliceFactory`'s adapter record `implements BookingSlice`, whose nested
/// `Request`/`Response` are inherited member types. By JLS 6.5.5.2 they shadow single-type imports, so a
/// SIMPLE name for the injected slice's `Request`/`Response` inside the generated `codec()` body would bind
/// to the HOST's types instead. Because the two slices declare those records with DIFFERENT arity, a
/// regression to simple names is a wrong-arity constructor / missing-accessor compile error.
///
/// The strongest assertion here is implicit: this module compiles its generated sources with javac, so if
/// the generator regressed, `BookingSliceFactory` would not compile, the module build would fail, and these
/// tests would not run at all. The explicit assertions pin the generated shape and the #394 source-
/// attribution breadcrumb (the generated header naming the originating `@Slice`).
class GeneratedInjectedSliceCodecTest {

    private static final String QUOTE_REQUEST = "com.example.injectedslice.QuoteSlice.Request";
    private static final String QUOTE_RESPONSE = "com.example.injectedslice.QuoteSlice.Response";
    private static final String HOST_FQN = "com.example.hostslice.BookingSlice";

    private static String factory;
    private static String routes;

    @BeforeAll
    static void readGeneratedSources() throws IOException {
        factory = Files.readString(locateGenerated("BookingSliceFactory.java"));
        routes = Files.readString(locateGenerated("BookingSliceRoutes.java"));
    }

    private static Path locateGenerated(String fileName) {
        var moduleDir = Paths.get(System.getProperty("user.dir"));
        var relative = Paths.get("target", "generated-sources", "annotations",
                                 "com", "example", "hostslice", fileName);
        var candidate = moduleDir.resolve(relative);
        if (Files.exists(candidate)) {
            return candidate;
        }
        // Reactor builds may run from the repo root; fall back to the module-qualified path.
        return moduleDir.resolve(Paths.get("jbct", "slice-processor-tests")).resolve(relative);
    }

    @Nested
    class InjectedSliceCodecFullyQualified {

        @Test
        void injectedResponse_isReferencedByFullyQualifiedName() {
            assertThat(factory).contains("new SliceCodec.TypeCodec<" + QUOTE_RESPONSE + ">(" + QUOTE_RESPONSE + ".class,");
            assertThat(factory).contains("return new " + QUOTE_RESPONSE + "(");
        }

        @Test
        void injectedRequest_isReferencedByFullyQualifiedName() {
            assertThat(factory).contains("new SliceCodec.TypeCodec<" + QUOTE_REQUEST + ">(" + QUOTE_REQUEST + ".class,");
            assertThat(factory).contains("return new " + QUOTE_REQUEST + "(");
        }

        @Test
        void injectedTypes_neverAppearAsShadowableBareNames() {
            // The buggy bare form would bind to the host's inherited Request/Response (wrong arity) and
            // would not compile — but assert against it explicitly to pin the failure to codegen intent.
            assertThat(factory).doesNotContain("new SliceCodec.TypeCodec<Response>(Response.class,");
            assertThat(factory).doesNotContain("new SliceCodec.TypeCodec<Request>(Request.class,");
        }
    }

    @Nested
    class RoutesCompileAndBind {

        @Test
        void hostRoute_isGeneratedForTheBookMethod() {
            assertThat(routes).contains(".named(\"book\")");
        }
    }

    @Nested
    class SourceAttribution {

        @Test
        void generatedFactory_headerNamesOriginatingSlice() {
            assertThat(factory).containsPattern("Generated by slice-processor \\S+ from @Slice " + Pattern.quote(HOST_FQN));
        }

        @Test
        void generatedRoutes_headerNamesOriginatingSlice() {
            assertThat(routes).containsPattern("Generated by slice-processor \\S+ from @Slice " + Pattern.quote(HOST_FQN));
        }
    }
}
