package org.pragmatica.aether.worker;

import org.pragmatica.aether.invoke.InvokeCodecs;
import org.pragmatica.aether.slice.SliceCodecs;
import org.pragmatica.aether.slice.blueprint.BlueprintCodecs;
import org.pragmatica.aether.worker.bootstrap.BootstrapCodecs;
import org.pragmatica.aether.worker.heartbeat.HeartbeatCodecs;
import org.pragmatica.aether.worker.mutation.MutationCodecs;
import org.pragmatica.cluster.metrics.MetricsCodecs;
import org.pragmatica.consensus.ConsensusCodecs;
import org.pragmatica.consensus.net.NetCodecs;
import org.pragmatica.consensus.rabia.RabiaCodecs;
import org.pragmatica.net.tcp.TcpCodecs;
import org.pragmatica.serialization.SliceCodec;
import org.pragmatica.serialization.SliceCodec.TypeCodec;
import org.pragmatica.swim.SwimCodecs;

import java.net.InetSocketAddress;
import java.util.ArrayList;

import static org.pragmatica.serialization.SliceCodec.deterministicTag;
import static org.pragmatica.serialization.SliceCodec.readCompact;
import static org.pragmatica.serialization.SliceCodec.readString;
import static org.pragmatica.serialization.SliceCodec.writeCompact;
import static org.pragmatica.serialization.SliceCodec.writeString;

/// Registry of all worker-level types for serialization.
/// Collects generated codec registries from dependencies and worker-specific types.
@SuppressWarnings("JBCT-STY-03") // KvstoreCodecs exists in two packages — FQCN unavoidable
public sealed interface WorkerCodecs {
    record unused() implements WorkerCodecs {}

    static SliceCodec workerCodecs(SliceCodec parent) {
        var all = new ArrayList<TypeCodec<?>>();
        // Generated registries from dependencies
        all.addAll(ConsensusCodecs.CODECS);
        all.addAll(RabiaCodecs.CODECS);
        all.addAll(NetCodecs.CODECS);
        all.addAll(TcpCodecs.CODECS);
        all.addAll(org.pragmatica.cluster.state.kvstore.KvstoreCodecs.CODECS);
        all.addAll(MetricsCodecs.CODECS);
        all.addAll(SliceCodecs.CODECS);
        all.addAll(org.pragmatica.aether.slice.kvstore.KvstoreCodecs.CODECS);
        all.addAll(BlueprintCodecs.CODECS);
        all.addAll(InvokeCodecs.CODECS);
        // Worker-specific codecs (generated by @Codec processor)
        all.addAll(MutationCodecs.CODECS);
        all.addAll(BootstrapCodecs.CODECS);
        all.addAll(HeartbeatCodecs.CODECS);
        // Worker metrics codecs (WorkerMetricsPing, WorkerMetricsPong, CommunityScaling*, etc.)
        all.addAll(org.pragmatica.aether.worker.metrics.MetricsCodecs.CODECS);
        // Network codecs (DHTRelayMessage)
        all.addAll(org.pragmatica.aether.worker.network.NetworkCodecs.CODECS);
        // DHT codecs
        all.addAll(org.pragmatica.dht.DhtCodecs.CODECS);
        // SWIM codecs
        all.addAll(SwimCodecs.CODECS);
        // Manual entry — JDK type without @Codec, uses createUnresolved to avoid DNS blocking
        all.add(inetSocketAddressCodec());
        return SliceCodec.sliceCodec(parent, all);
    }

    /// InetSocketAddress codec — uses createUnresolved to avoid blocking DNS on deserialization.
    /// Wire format: hostname (string) + port (compact int).
    private static TypeCodec<InetSocketAddress> inetSocketAddressCodec() {
        return new TypeCodec<>(InetSocketAddress.class,
                               deterministicTag("java.net.InetSocketAddress"),
                               (codec, buf, val) -> {
                                   writeString(buf, val.getHostString());
                                   writeCompact(buf, val.getPort());
                               },
                               (codec, buf) -> InetSocketAddress.createUnresolved(readString(buf), readCompact(buf)));
    }
}
