// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.http.handler;

import org.pragmatica.lang.Promise;

import java.util.List;


/// Handler for HTTP requests routed through the cluster.
///
/// Implementations are generated by annotation processor. The handler:
///
///   - Extracts parameters from raw HTTP request
///   - Calls business logic
///   - Returns response data
///
public interface HttpRequestHandler {
    Promise<HttpResponseData> handle(HttpRequestContext ctx);
    List<HttpRouteDefinition> routes();
}
