package org.pragmatica.aether.http.handler;

import org.pragmatica.lang.Promise;

import java.util.List;


/// Handler for HTTP requests routed through the cluster.
///
/// Implementations are generated by annotation processor. The handler:
///
///   - Extracts parameters from raw HTTP request
///   - Calls business logic
///   - Returns response data
///
public interface HttpRequestHandler {
    Promise<HttpResponseData> handle(HttpRequestContext ctx);
    List<HttpRouteDefinition> routes();
}
