// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.http.handler;

import org.pragmatica.aether.slice.SliceInvokerFacade;


/// Factory for creating HTTP request handlers.
///
/// Generated by annotation processor from slice route configuration.
/// Takes SliceInvokerFacade to enable cross-node request routing.
public interface HttpRequestHandlerFactory {
    HttpRequestHandler create(SliceInvokerFacade invoker);
}
