package org.pragmatica.aether.http.handler;

import org.pragmatica.lang.Promise;

import java.util.List;

/// Handler for HTTP requests routed through the cluster.
///
/// Implementations are generated by annotation processor. The handler:
///
///   - Extracts parameters from raw HTTP request
///   - Calls business logic
///   - Returns response data
///
public interface HttpRequestHandler {
    /// Handle an HTTP request.
    ///
    /// @param ctx raw HTTP request context
    /// @return promise of response data
    Promise<HttpResponseData> handle(HttpRequestContext ctx);

    /// Get route definitions for KV-Store registration.
    ///
    /// Called during slice activation to publish routes.
    ///
    /// @return list of route definitions
    List<HttpRouteDefinition> routes();
}
