// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.

package org.pragmatica.aether.cli.cluster;

import org.junit.jupiter.api.Test;
import org.pragmatica.aether.cli.cluster.ClusterBootstrapOrchestrator.BootstrapContext;
import org.pragmatica.aether.config.cluster.AutoHealSpec;
import org.pragmatica.aether.config.cluster.CloudProviderName;
import org.pragmatica.aether.config.cluster.ClusterBootstrapConfig;
import org.pragmatica.aether.config.cluster.ClusterIdentity;
import org.pragmatica.aether.config.cluster.CoreTopology;
import org.pragmatica.aether.config.cluster.InfrastructureConfig;
import org.pragmatica.aether.config.cluster.LoadBalancerMode;
import org.pragmatica.aether.config.cluster.NetworkingType;
import org.pragmatica.aether.config.cluster.NodeRole;
import org.pragmatica.aether.config.cluster.OperationsConfig;
import org.pragmatica.aether.config.cluster.PortMapping;
import org.pragmatica.aether.config.cluster.RoleSubTable;
import org.pragmatica.aether.config.cluster.SourceProfile;
import org.pragmatica.aether.config.cluster.SourceType;
import org.pragmatica.aether.config.cluster.TimeoutsConfig;
import org.pragmatica.aether.config.cluster.TlsDeploymentConfig;
import org.pragmatica.aether.environment.NodeAddress;
import org.pragmatica.lang.Option;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.pragmatica.aether.environment.ClusterName.clusterName;
import static org.pragmatica.aether.environment.SourceName.sourceNameOrDefault;

/// #998 — the PERSISTED management endpoint.
///
/// The defect: `registerClusterLocally` and `buildResult` each built the endpoint themselves, and only
/// `buildResult` appended `operations.ports.management`. So every cluster was REGISTERED in
/// `~/.aether/clusters.toml` as `<scheme>://<ip>` with no port, every later registry-based management call
/// resolved that entry and hit the scheme default — 443 under auto-generated TLS — and the management API
/// was on 8080. Observed live on 2026-09-11: `cluster destroy` could not enumerate nodes, so DRAIN_NODES
/// and SHUTDOWN_NODES were skipped and three paid VMs were deleted without a graceful drain.
///
/// These pin the ENDPOINT STRING rather than the registry write, deliberately: `registerClusterLocally`
/// writes the real `~/.aether/clusters.toml`, and a test that drove it would overwrite the operator's
/// registry. `managementEndpoint` is the whole of the computation and is pure.
class BootstrapPhasePostEndpointTest {
    private static final String PUBLIC_IP = "138.199.236.244";

    /// THE regression, in the shape the live cluster had it: auto-generated TLS, one collected address.
    /// `https://138.199.236.244` is what was written; `https://138.199.236.244:8080` is what the API answers.
    @Test
    void managementEndpoint_carriesTheManagementPort_forACollectedAddress() {
        assertThat(BootstrapPhasePost.managementEndpoint(context(true, PortMapping.defaultPortMapping(), PUBLIC_IP)))
                  .as("the persisted endpoint must name the port the management API listens on, or every "
                      + "registry-based call silently targets 443")
                  .isEqualTo("https://" + PUBLIC_IP + ":8080");
    }

    /// The port must be READ, not restated. A hardcoded `:8080` passes the test above and fails this one,
    /// which is the only reason that test is evidence about the config rather than about a literal.
    @Test
    void managementEndpoint_honoursANonDefaultManagementPort() {
        assertThat(BootstrapPhasePost.managementEndpoint(context(true,
                                                                PortMapping.portMapping(8090, 9100, 8070, 8190),
                                                                PUBLIC_IP)))
                  .as("operations.ports.management is the source of truth; a literal would make this "
                      + "endpoint unreachable for every cluster that moves the port")
                  .isEqualTo("https://" + PUBLIC_IP + ":9100");
    }

    /// #209's property, re-pinned through the refactor: the scheme still follows `tls.autoGenerate`. One
    /// builder now serves both the registry and the result, so this is the test that would catch the
    /// consolidation having dropped the scheme branch.
    @Test
    void managementEndpoint_usesHttp_whenTlsIsNotAutoGenerated() {
        assertThat(BootstrapPhasePost.managementEndpoint(context(false, PortMapping.defaultPortMapping(), PUBLIC_IP)))
                  .as("#209: the registered scheme must be the one the cluster actually serves")
                  .isEqualTo("http://" + PUBLIC_IP + ":8080");
    }

    /// The no-address fallback carried a hardcoded `9090`, which is not the management port under any
    /// configuration — `PortMapping.defaultPortMapping()` is 8080. Asserted as an inequality too, because
    /// "equals the configured port" and "is not 9090" fail for different reasons and the second is the one
    /// that names the bug.
    @Test
    void managementEndpoint_localhostFallback_readsTheConfiguredPort_notAHardcoded9090() {
        var endpoint = BootstrapPhasePost.managementEndpoint(contextWithoutAddresses());

        assertThat(endpoint).as("the fallback must read the same config as every other branch")
                  .isEqualTo("https://localhost:8080");
        assertThat(endpoint).as("9090 was never the management port; it was a literal nobody had read")
                  .doesNotContain("9090");
    }

    /// The SYMMETRY #998 was the absence of: the endpoint the bootstrap REPORTS and the endpoint it
    /// REGISTERS are one value. Two constructions of it is what allowed them to drift for the whole of
    /// rc1-rc4, with the reported one correct and the persisted one broken.
    @Test
    void buildResult_reportsTheSameEndpointTheRegistryRecords() {
        var ctx = context(true, PortMapping.defaultPortMapping(), PUBLIC_IP);

        assertThat(BootstrapPhasePost.buildResult(ctx).endpoint())
                  .as("the reported and the persisted endpoint must be the same string; they were not, and "
                      + "only the persisted one was ever used by a later command")
                  .isEqualTo(BootstrapPhasePost.managementEndpoint(ctx));
    }

    private static BootstrapContext context(boolean autoGenerateTls, PortMapping ports, String publicIp) {
        return BootstrapContext.bootstrapContext(config(autoGenerateTls, ports),
                                                 state(),
                                                 List.of(),
                                                 List.of(NodeAddress.nodeAddress("eu-1-core-0",
                                                                                 publicIp,
                                                                                 Option.empty())));
    }

    private static BootstrapContext contextWithoutAddresses() {
        return BootstrapContext.bootstrapContext(config(true, PortMapping.defaultPortMapping()),
                                                 state(),
                                                 List.of(),
                                                 List.of());
    }

    private static BootstrapState state() {
        return BootstrapState.initialState(clusterName("endpoint-probe").unwrap(), "hash", "2026-09-11T00:00:00Z");
    }

    private static ClusterBootstrapConfig config(boolean autoGenerateTls, PortMapping ports) {
        var ops = OperationsConfig.operationsConfig(AutoHealSpec.defaultAutoHealSpec(),
                                                    TlsDeploymentConfig.tlsDeploymentConfig(autoGenerateTls, "720h"),
                                                    TimeoutsConfig.timeoutsConfig("3s", "10s", "10s"),
                                                    ports);

        return ClusterBootstrapConfig.clusterBootstrapConfig("1.0.0",
                                                             ClusterIdentity.clusterIdentity("endpoint-probe", "1.0.0").unwrap(),
                                                             CoreTopology.defaultCoreTopology(),
                                                             Map.of("eu-1", cloudSource()),
                                                             Map.of(),
                                                             InfrastructureConfig.infrastructureConfig(NetworkingType.MANUAL),
                                                             ops);
    }

    private static SourceProfile cloudSource() {
        return SourceProfile.sourceProfile(sourceNameOrDefault("eu-1"),
                                           SourceType.CLOUD,
                                           Option.some(CloudProviderName.HETZNER),
                                           Option.empty(),
                                           Option.empty(),
                                           Option.empty(),
                                           Option.empty(),
                                           Option.empty(),
                                           Option.empty(),
                                           LoadBalancerMode.NONE,
                                           List.of(),
                                           Option.empty(),
                                           Map.of(),
                                           Map.of(NodeRole.CORE,
                                                  RoleSubTable.roleSubTable(NodeRole.CORE,
                                                                            Option.some(3),
                                                                            Option.empty(),
                                                                            Option.empty(),
                                                                            "default")),
                                           List.of(),
                                           Option.empty());
    }
}
