package org.pragmatica.jbct.maven;

import java.util.Properties;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/// #1778: `slice-deps.properties` goes into the slice jar, so it must be the same bytes for the same dependencies.
class CollectSliceDepsReproducibleTextTest {
    @Test
    void reproducibleText_hasNoDateLine_andSortsEntries() throws Exception {
        var mappings = new Properties();

        mappings.setProperty("org.example.B", "g:b:1.0.0");
        mappings.setProperty("org.example.A", "g:a:1.0.0");

        var text = CollectSliceDepsMojo.reproducibleText(mappings).unwrap();

        assertThat(text).startsWith("#Generated by jbct:collect-slice-deps\n");
        assertThat(text).doesNotContainPattern("#\\w{3} \\w{3} \\d");
        assertThat(text.indexOf("org.example.A")).isLessThan(text.indexOf("org.example.B"));

        Thread.sleep(1100);

        assertThat(CollectSliceDepsMojo.reproducibleText(mappings).unwrap()).isEqualTo(text);
    }
}
