// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.

package org.pragmatica.aether.pg.schema.builder;

import org.junit.jupiter.api.Test;
import org.pragmatica.aether.pg.schema.model.Column;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;


/// Exercises identity/generated-column recognition in DdlAnalyzer. These properties
/// feed the @PgSql factory generator's NOT-NULL coverage check — auto-populated
/// columns must be exempted from INSERT/SAVE record shapes.
class DdlAnalyzerIdentityTest {

    @Test
    void generatedAlwaysAsIdentity_isRecognisedAsIdentityColumn() {
        var schema = MigrationProcessor.create().processAll(List.of(
            "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)"
        )).unwrap();
        var idCol = schema.table("t").unwrap().column("id").unwrap();
        assertThat(idCol.identity().isPresent()).as("id column identity spec").isTrue();
        assertThat(idCol.identity().unwrap().kind()).isEqualTo(Column.IdentityKind.ALWAYS);
        assertThat(idCol.nullable()).isFalse();
    }

    @Test
    void generatedByDefaultAsIdentity_isRecognisedAsByDefault() {
        var schema = MigrationProcessor.create().processAll(List.of(
            "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)"
        )).unwrap();
        var idCol = schema.table("t").unwrap().column("id").unwrap();
        assertThat(idCol.identity().isPresent()).as("id column identity spec").isTrue();
        assertThat(idCol.identity().unwrap().kind()).isEqualTo(Column.IdentityKind.BY_DEFAULT);
        assertThat(idCol.nullable()).isFalse();
    }

    @Test
    void generatedAlwaysAsStored_populatesGeneratedExpr() {
        var schema = MigrationProcessor.create().processAll(List.of(
            "CREATE TABLE t (a NUMERIC NOT NULL, b NUMERIC GENERATED ALWAYS AS (a*2) STORED)"
        )).unwrap();
        var bCol = schema.table("t").unwrap().column("b").unwrap();
        assertThat(bCol.generatedExpr().isPresent()).as("b column generated expression").isTrue();
        assertThat(bCol.identity().isPresent()).isFalse();
        assertThat(bCol.nullable()).isFalse();
    }

    @Test
    void plainBigintColumn_hasNoIdentityOrGenerated() {
        var schema = MigrationProcessor.create().processAll(List.of(
            "CREATE TABLE t (id BIGINT PRIMARY KEY, name TEXT NOT NULL)"
        )).unwrap();
        var idCol = schema.table("t").unwrap().column("id").unwrap();
        assertThat(idCol.identity().isPresent()).isFalse();
        assertThat(idCol.generatedExpr().isPresent()).isFalse();
    }
}
