CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status TEXT NOT NULL,
    total NUMERIC NOT NULL,
    correlation_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE events (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    event_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE items (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE posts (
    id BIGINT PRIMARY KEY,
    tags TEXT[]
);

CREATE TABLE ranks (
    id BIGINT PRIMARY KEY,
    scores INTEGER[]
);

CREATE TABLE ledger (
    account_id UUID NOT NULL,
    amount NUMERIC NOT NULL
);

CREATE TABLE events_uuid (
    id UUID PRIMARY KEY,
    amount NUMERIC NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE blobs (
    id BIGINT PRIMARY KEY,
    payload BYTEA NOT NULL
);

CREATE TABLE foos (
    id BIGINT PRIMARY KEY,
    f TEXT NOT NULL
);

CREATE TABLE schema_versions (
    version BIGINT NOT NULL
);

-- Wide table (31 columns) for row-mapper batching tests that must cross the
-- Result.all arity-15 ceiling (16 columns -> 2 tuple parts, 31 -> 3 parts).
CREATE TABLE wide (
    f0 BIGINT PRIMARY KEY,
    f1 BIGINT NOT NULL, f2 BIGINT NOT NULL, f3 BIGINT NOT NULL, f4 BIGINT NOT NULL,
    f5 BIGINT NOT NULL, f6 BIGINT NOT NULL, f7 BIGINT NOT NULL, f8 BIGINT NOT NULL,
    f9 BIGINT NOT NULL, f10 BIGINT NOT NULL, f11 BIGINT NOT NULL, f12 BIGINT NOT NULL,
    f13 BIGINT NOT NULL, f14 BIGINT NOT NULL, f15 BIGINT NOT NULL, f16 BIGINT NOT NULL,
    f17 BIGINT NOT NULL, f18 BIGINT NOT NULL, f19 BIGINT NOT NULL, f20 BIGINT NOT NULL,
    f21 BIGINT NOT NULL, f22 BIGINT NOT NULL, f23 BIGINT NOT NULL, f24 BIGINT NOT NULL,
    f25 BIGINT NOT NULL, f26 BIGINT NOT NULL, f27 BIGINT NOT NULL, f28 BIGINT NOT NULL,
    f29 BIGINT NOT NULL, f30 BIGINT NOT NULL
);
