// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.generatedgate;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import java.util.stream.Stream;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.io.TempDir;
import org.pragmatica.jbct.cli.JbctCommand;

import picocli.CommandLine;

import static org.assertj.core.api.Assertions.assertThat;

/// #1998: the project a first user gets from `jbct init` and `jbct add-*` must build, with its own format-check and lint.
///
/// Every variant is generated by the REAL commands (`JbctCommand`, in-process) and then built by a real Maven child
/// process, `mvn verify`, against the repository this reactor has just installed into. `verify` runs the project's own
/// `format-check` and `lint` (bound by the generated pom), compiles with the annotation processors, runs the generated tests and
/// packages the slices. A template that drifts from the formatter, the linter or the dependencies it needs fails HERE, not on the
/// first cold-user build.
///
/// Variants (each is a separate dynamic test, built in parallel):
///   - `jbct init` (slice), `jbct init --no-slice`, `jbct init --with-persistence`;
///   - `jbct add-slice`, `jbct add-event`, `jbct add-persistence`, each on a fresh `init`;
///   - all three adds on one project.
/// Not covered: AI-tool installation (`jbct init` without `--no-ai` downloads from GitHub and writes no build input).
///
/// A gate that cannot see is worse than none (every defect it exists for is a project that did not build), so a green variant
/// must show the build RAN the project's gates (`format-check` and `lint` executions in the log) and that the generated files
/// the variant promises exist.
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GeneratedProjectsBuildIT {
    private static final String VERSION = require("gate.version");
    private static final Path MAVEN = Path.of(require("gate.maven.home"), "bin", "mvn");
    private static final String REPOSITORY = require("gate.repo.local");
    private static final int PARALLEL_BUILDS = Integer.getInteger("gate.parallel", 4);
    private static final long BUILD_TIMEOUT_MINUTES = 20;

    /// One step of a variant: the `jbct` arguments, given the project directory.
    private record Step(String label, Function<Path, List<String>> arguments) {}

    private record Variant(String name, List<Step> steps, List<String> expectedFiles) {}

    private record Outcome(String name, String failedStep, int buildExit, Path log, long millis) {}

    private Path work;

    private final Map<String, Outcome> outcomes = new ConcurrentHashMap<>();

    @BeforeAll
    void generateAndBuildEveryVariant(@TempDir Path tempDir) throws Exception {
        work = tempDir;

        var variants = variants();
        var pool = Executors.newFixedThreadPool(PARALLEL_BUILDS);

        try {
            var futures = new ArrayList<Future<?>>();

            for (var variant : variants) {
                futures.add(pool.submit(() -> outcomes.put(variant.name(), run(variant))));
            }

            for (var future : futures) {
                future.get(BUILD_TIMEOUT_MINUTES * variants.size(), TimeUnit.MINUTES);
            }

            outcomes.values()
                    .stream()
                    .sorted(java.util.Comparator.comparing(Outcome::name))
                    .forEach(outcome -> System.out.printf("GENERATED-GATE %-24s %6d ms  build exit %d%n", outcome.name(), outcome.millis(), outcome.buildExit()));
        } finally {
            pool.shutdownNow();
        }
    }

    @TestFactory
    Stream<DynamicTest> everyGeneratedProject_buildsWithItsOwnFormatCheckAndLint() {
        return variants().stream()
                         .map(variant -> DynamicTest.dynamicTest(variant.name(), () -> verify(variant, outcomes.get(variant.name()))));
    }

    private void verify(Variant variant, Outcome outcome) throws IOException {
        assertThat(outcome).as("variant %s was run", variant.name()).isNotNull();
        assertThat(outcome.failedStep()).as("every `jbct` step of %s succeeds (log %s)", variant.name(), outcome.log()).isNull();

        var log = Files.readString(outcome.log());

        assertThat(outcome.buildExit()).as("`mvn verify` of the project generated for %s succeeds; errors:%n%s", variant.name(), errors(log))
                                       .isZero();
        assertThat(log).as("the build of %s ran the project's own format-check", variant.name()).containsPattern("--- .*:format-check ");
        assertThat(log).as("the build of %s ran the project's own lint", variant.name()).containsPattern("--- .*:lint ");
        assertThat(log).as("the build of %s ends in BUILD SUCCESS", variant.name()).contains("BUILD SUCCESS");

        var generated = generatedFileNames(outcome.log().getParent());

        assertThat(generated).as("the generated project of %s holds the files its commands promise", variant.name())
                             .containsAll(variant.expectedFiles());
    }

    private static List<String> generatedFileNames(Path projectDir) throws IOException {
        try (var files = Files.walk(projectDir.resolve("src"))) {
            return files.filter(Files::isRegularFile).map(path -> path.getFileName().toString()).toList();
        }
    }

    private static String errors(String log) {
        return log.lines()
                  .filter(line -> line.contains("[ERROR]") || line.contains("[WARNING] The requested profile"))
                  .limit(30)
                  .reduce("", (all, line) -> all + line + "\n");
    }

    private Outcome run(Variant variant) {
        var started = System.nanoTime();
        var dir = work.resolve(variant.name());
        var log = dir.resolve("build.log");

        try {
            Files.createDirectories(dir.getParent());

            for (var step : variant.steps()) {
                var exit = new CommandLine(new JbctCommand()).setCaseInsensitiveEnumValuesAllowed(true).execute(step.arguments().apply(dir).toArray(String[]::new));

                if (exit != 0) {
                    Files.createDirectories(dir);
                    Files.writeString(log, "jbct step '" + step.label() + "' exited " + exit);

                    return new Outcome(variant.name(), step.label(), -1, log, millisSince(started));
                }
            }

            return new Outcome(variant.name(), null, build(dir, log), log, millisSince(started));
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }

            return new Outcome(variant.name(), "exception: " + e, -1, log, millisSince(started));
        }
    }

    private static int build(Path dir, Path log) throws IOException, InterruptedException {
        var process = new ProcessBuilder(MAVEN.toString(), "-B", "--no-transfer-progress", "-Dmaven.repo.local=" + REPOSITORY, "verify")
                          .directory(dir.toFile())
                          .redirectErrorStream(true)
                          .redirectOutput(log.toFile())
                          .start();

        if (!process.waitFor(BUILD_TIMEOUT_MINUTES, TimeUnit.MINUTES)) {
            process.destroyForcibly();

            return -2;
        }

        return process.exitValue();
    }

    private static long millisSince(long startedNanos) {
        return (System.nanoTime() - startedNanos) / 1_000_000L;
    }

    // --- the variants -----------------------------------------------------------------------------------------------------

    private static List<Variant> variants() {
        var init = init(false, false);
        var persistence = List.of("SamplePersistence.java");
        var addSlice = new Step("add-slice", dir -> List.of("add-slice", "-d", dir.toString(), "Analytics"));
        var addEvent = new Step("add-event", dir -> List.of("add-event", "-d", dir.toString(), "order-created"));
        var addPersistence = new Step("add-persistence", dir -> List.of("add-persistence", "-d", dir.toString()));

        var everything = new ArrayList<>(persistence);

        everything.addAll(List.of("Analytics.java", "OrderCreatedPublisher.java"));

        return List.of(new Variant("init-slice", List.of(init), List.of("HelloWorld.java")),
                       new Variant("init-no-slice", List.of(init(true, false)), List.of()),
                       new Variant("init-with-persistence", List.of(init(false, true)), concat(List.of("HelloWorld.java"), persistence)),
                       new Variant("init-add-slice", List.of(init, addSlice), List.of("HelloWorld.java", "Analytics.java")),
                       new Variant("init-add-event", List.of(init, addEvent), List.of("OrderCreatedPublisher.java", "OrderCreatedSubscription.java")),
                       new Variant("init-add-persistence", List.of(init, addPersistence), concat(List.of("HelloWorld.java"), persistence)),
                       new Variant("init-add-everything", List.of(init, addSlice, addEvent, addPersistence), everything));
    }

    private static List<String> concat(List<String> first, List<String> second) {
        var all = new ArrayList<>(first);

        all.addAll(second);

        return all;
    }

    private static Step init(boolean noSlice, boolean withPersistence) {
        return new Step("init", dir -> {
            var args = new ArrayList<>(List.of("init", "--no-ai", "-g", "com.example", "-a", dir.getFileName().toString(),
                                               "--aether-version", VERSION, "--jbct-version", VERSION, "--pragmatica-version", VERSION));

            if (noSlice) {
                args.add("--no-slice");
            }

            if (withPersistence) {
                args.add("--with-persistence");
            }

            args.add(dir.toString());

            return args;
        });
    }

    private static String require(String property) {
        var value = System.getProperty(property);

        if (value == null || value.isBlank()) {
            throw new IllegalStateException("system property " + property + " is not set; it comes from the failsafe configuration of generated-project-gate/pom.xml");
        }

        return value;
    }
}
