// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.pg.codegen;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.pragmatica.aether.pg.schema.model.BuiltinTypes;
import org.pragmatica.aether.pg.schema.model.PgType;
import org.pragmatica.lang.Option;


public final class TypeMapper {
    private TypeMapper() {}

    public record JavaTypeInfo(String typeName,
                               String boxedTypeName,
                               boolean primitive,
                               Option<String> importStatement,
                               String rowAccessorMethod,
                               Option<String> rowAccessorTypeArg) {}

    private static final Map<String, JavaTypeInfo> MAPPINGS = Map.ofEntries(entry("smallint",
                                                                                  "short",
                                                                                  "Short",
                                                                                  true,
                                                                                  Option.present("java.lang.Short"),
                                                                                  "getObject",
                                                                                  Option.present("Short.class")),
                                                                            entry("integer",
                                                                                  "int",
                                                                                  "Integer",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getInt",
                                                                                  Option.empty()),
                                                                            entry("bigint",
                                                                                  "long",
                                                                                  "Long",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getLong",
                                                                                  Option.empty()),
                                                                            entry("real",
                                                                                  "float",
                                                                                  "Float",
                                                                                  true,
                                                                                  Option.present("java.lang.Float"),
                                                                                  "getObject",
                                                                                  Option.present("Float.class")),
                                                                            entry("double precision",
                                                                                  "double",
                                                                                  "Double",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getDouble",
                                                                                  Option.empty()),
                                                                            entry("numeric",
                                                                                  "java.math.BigDecimal",
                                                                                  "java.math.BigDecimal",
                                                                                  false,
                                                                                  Option.present("java.math.BigDecimal"),
                                                                                  "getObject",
                                                                                  Option.present("java.math.BigDecimal.class")),
                                                                            entry("money",
                                                                                  "java.math.BigDecimal",
                                                                                  "java.math.BigDecimal",
                                                                                  false,
                                                                                  Option.present("java.math.BigDecimal"),
                                                                                  "getObject",
                                                                                  Option.present("java.math.BigDecimal.class")),
                                                                            entry("smallserial",
                                                                                  "short",
                                                                                  "Short",
                                                                                  true,
                                                                                  Option.present("java.lang.Short"),
                                                                                  "getObject",
                                                                                  Option.present("Short.class")),
                                                                            entry("serial",
                                                                                  "int",
                                                                                  "Integer",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getInt",
                                                                                  Option.empty()),
                                                                            entry("bigserial",
                                                                                  "long",
                                                                                  "Long",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getLong",
                                                                                  Option.empty()),
                                                                            entry("text",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("varchar",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("char",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("name",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("citext",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("boolean",
                                                                                  "boolean",
                                                                                  "Boolean",
                                                                                  true,
                                                                                  Option.empty(),
                                                                                  "getBoolean",
                                                                                  Option.empty()),
                                                                            entry("date",
                                                                                  "java.time.LocalDate",
                                                                                  "java.time.LocalDate",
                                                                                  false,
                                                                                  Option.present("java.time.LocalDate"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.LocalDate.class")),
                                                                            entry("timestamp",
                                                                                  "java.time.LocalDateTime",
                                                                                  "java.time.LocalDateTime",
                                                                                  false,
                                                                                  Option.present("java.time.LocalDateTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.LocalDateTime.class")),
                                                                            entry("timestamp without time zone",
                                                                                  "java.time.LocalDateTime",
                                                                                  "java.time.LocalDateTime",
                                                                                  false,
                                                                                  Option.present("java.time.LocalDateTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.LocalDateTime.class")),
                                                                            entry("timestamptz",
                                                                                  "java.time.Instant",
                                                                                  "java.time.Instant",
                                                                                  false,
                                                                                  Option.present("java.time.Instant"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.Instant.class")),
                                                                            entry("timestamp with time zone",
                                                                                  "java.time.Instant",
                                                                                  "java.time.Instant",
                                                                                  false,
                                                                                  Option.present("java.time.Instant"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.Instant.class")),
                                                                            entry("time",
                                                                                  "java.time.LocalTime",
                                                                                  "java.time.LocalTime",
                                                                                  false,
                                                                                  Option.present("java.time.LocalTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.LocalTime.class")),
                                                                            entry("time without time zone",
                                                                                  "java.time.LocalTime",
                                                                                  "java.time.LocalTime",
                                                                                  false,
                                                                                  Option.present("java.time.LocalTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.LocalTime.class")),
                                                                            entry("timetz",
                                                                                  "java.time.OffsetTime",
                                                                                  "java.time.OffsetTime",
                                                                                  false,
                                                                                  Option.present("java.time.OffsetTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.OffsetTime.class")),
                                                                            entry("time with time zone",
                                                                                  "java.time.OffsetTime",
                                                                                  "java.time.OffsetTime",
                                                                                  false,
                                                                                  Option.present("java.time.OffsetTime"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.OffsetTime.class")),
                                                                            entry("interval",
                                                                                  "java.time.Duration",
                                                                                  "java.time.Duration",
                                                                                  false,
                                                                                  Option.present("java.time.Duration"),
                                                                                  "getObject",
                                                                                  Option.present("java.time.Duration.class")),
                                                                            entry("uuid",
                                                                                  "java.util.UUID",
                                                                                  "java.util.UUID",
                                                                                  false,
                                                                                  Option.present("java.util.UUID"),
                                                                                  "getObject",
                                                                                  Option.present("java.util.UUID.class")),
                                                                            entry("json",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("jsonb",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("bytea",
                                                                                  "byte[]",
                                                                                  "byte[]",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getBytes",
                                                                                  Option.empty()),
                                                                            entry("inet",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("cidr",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("macaddr",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("tsvector",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("tsquery",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()),
                                                                            entry("xml",
                                                                                  "String",
                                                                                  "String",
                                                                                  false,
                                                                                  Option.empty(),
                                                                                  "getString",
                                                                                  Option.empty()));

    public static Option<JavaTypeInfo> map(PgType type) {
        return switch (type) {
            case PgType.BuiltinType bt -> {
                var canonical = BuiltinTypes.canonicalize(bt.name());
                var info = MAPPINGS.get(canonical);

                yield info != null
                      ? Option.present(info)
                      : Option.empty();
            }
            case PgType.ArrayType at -> map(at.elementType()).map(elem -> new JavaTypeInfo(elem.typeName() + "[]",
                                                                                           elem.boxedTypeName() + "[]",
                                                                                           false,
                                                                                           elem.importStatement(),
                                                                                           "getObject",
                                                                                           Option.present(elem.typeName()
                                                                                                         + "[].class")));
            case PgType.EnumType _ -> Option.present(new JavaTypeInfo("String",
                                                                      "String",
                                                                      false,
                                                                      Option.empty(),
                                                                      "getString",
                                                                      Option.empty()));
            default -> Option.present(new JavaTypeInfo("String",
                                                       "String",
                                                       false,
                                                       Option.empty(),
                                                       "getString",
                                                       Option.empty()));
        };
    }

    public static Option<JavaTypeInfo> mapNullable(PgType type, CodegenConfig.NullableStyle style) {
        return map(type).map(info -> boxIfNeeded(info, style));
    }

    private static JavaTypeInfo boxIfNeeded(JavaTypeInfo info, CodegenConfig.NullableStyle style) {
        if (style != CodegenConfig.NullableStyle.OPTION || !info.primitive()) {
            return info;
        }

        return new JavaTypeInfo(info.boxedTypeName(),
                                info.boxedTypeName(),
                                false,
                                info.importStatement(),
                                info.rowAccessorMethod(),
                                info.rowAccessorTypeArg());
    }

    public static Set<String> importsFor(JavaTypeInfo info) {
        var imports = new HashSet<String>();

        info.importStatement().onPresent(imports::add);

        return imports;
    }

    private static Map.Entry<String, JavaTypeInfo> entry(String pgType,
                                                         String javaType,
                                                         String boxedType,
                                                         boolean primitive,
                                                         Option<String> importStmt,
                                                         String accessor,
                                                         Option<String> typeArg) {
        return Map.entry(pgType, new JavaTypeInfo(javaType, boxedType, primitive, importStmt, accessor, typeArg));
    }
}
