// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 Pragmatica Labs - Sergiy Yevtushenko
// Licensed under Business Source License 1.1. Change Date: 2030-01-01. Change License: Apache-2.0.
// See LICENSE in the repository root for full terms.
package org.pragmatica.aether.cli.cluster;

import org.pragmatica.lang.Contract;

import java.util.stream.IntStream;


/// Renders a ready-to-use docker-compose YAML for an Aether cluster.
///
/// Every node service carries both `aether.cluster=<name>` and `aether.node-id=node-N`
/// labels, matching the convention used by `DockerComputeProvider.buildRunCommand` for
/// CTM-provisioned replacements. Cross-cluster tooling (`docker ps --filter
/// label=aether.cluster=<name>`) can unambiguously enumerate this cluster's containers
/// regardless of whether they were compose-deployed or CTM-spawned.
///
/// Output is intentionally minimal: no PostgreSQL service, no LB sidecar, no env-var
/// substitution. Operators copy the file, adjust for their environment (storage volumes,
/// healthchecks, secrets), then run `docker compose up -d`. The label structure is the
/// correct-by-construction part — the rest is operator preference.
final class DockerComposeTemplate {
    private DockerComposeTemplate() {}

    @Contract
    static String render(String clusterName,
                         int nodes,
                         String image,
                         int mgmtPortBase,
                         int appPortBase,
                         int clusterPort) {
        var sb = new StringBuilder(2048);
        appendHeader(sb, clusterName, nodes);
        appendCommon(sb, clusterName, nodes, image, clusterPort);
        sb.append("services:\n");
        IntStream.rangeClosed(1, nodes).forEach(i -> appendNode(sb, clusterName, i, mgmtPortBase, appPortBase));
        sb.append("\nnetworks:\n");
        sb.append("  aether-").append(clusterName).append("-network:\n");
        sb.append("    driver: bridge\n");

        return sb.toString();
    }

    private static void appendHeader(StringBuilder sb, String clusterName, int nodes) {
        sb.append("# Aether cluster '").append(clusterName).append("' - ").append(nodes).append(" nodes\n");
        sb.append("#\n");
        sb.append("# Generated by `aether cluster scaffold --name ").append(clusterName).append(" --format docker-compose`.\n");
        sb.append("# Every service carries `aether.cluster=").append(clusterName).append("` + `aether.node-id=node-N` labels,\n");
        sb.append("# matching what DockerComputeProvider sets on CTM-provisioned replacements. This lets\n");
        sb.append("# tooling enumerate ALL of this cluster's containers (compose-deployed + CTM-spawned)\n");
        sb.append("# unambiguously via `docker ps --filter label=aether.cluster=").append(clusterName).append("`.\n");
        sb.append("#\n");
        sb.append("# Usage: docker compose -f compose.yml up -d\n");
        sb.append("\n");
    }

    private static void appendCommon(StringBuilder sb, String clusterName, int nodes, String image, int clusterPort) {
        sb.append("x-node-common: &node-common\n");
        sb.append("  image: ").append(image).append("\n");
        sb.append("  networks:\n");
        sb.append("    - aether-").append(clusterName).append("-network\n");
        sb.append("  environment: &node-env\n");
        sb.append("    CLUSTER_PORT: \"").append(clusterPort).append("\"\n");
        sb.append("    MANAGEMENT_PORT: \"8080\"\n");
        sb.append("    PEERS: \"").append(buildPeers(clusterName, nodes, clusterPort)).append("\"\n");
        sb.append("    CORE_MAX: \"").append(nodes).append("\"\n");
        sb.append("    AETHER_CLUSTER_SECRET: \"change-me-cluster-secret\"\n");
        sb.append("  # restart: \"no\" - Aether's CTM auto-heal owns failure recovery; do NOT enable container\n");
        sb.append("  # restart policies. See aether/docs/operator/deployment-recovery.md.\n");
        sb.append("  restart: \"no\"\n");
        sb.append("\n");
    }

    private static void appendNode(StringBuilder sb, String clusterName, int idx, int mgmtPortBase, int appPortBase) {
        var name = "aether-" + clusterName + "-node-" + idx;
        var nodeId = "node-" + idx;
        sb.append("  ").append(name).append(":\n");
        sb.append("    <<: *node-common\n");
        sb.append("    container_name: ").append(name).append("\n");
        sb.append("    hostname: ").append(name).append("\n");
        sb.append("    labels:\n");
        sb.append("      aether.cluster: \"").append(clusterName).append("\"\n");
        sb.append("      aether.node-id: \"").append(nodeId).append("\"\n");
        sb.append("    environment:\n");
        sb.append("      <<: *node-env\n");
        sb.append("      NODE_ID: \"").append(nodeId).append("\"\n");
        sb.append("    ports:\n");
        sb.append("      - \"").append(mgmtPortBase + idx - 1).append(":8080\"\n");
        sb.append("      - \"").append(appPortBase + idx - 1).append(":8070\"\n");
        sb.append("\n");
    }

    private static String buildPeers(String clusterName, int nodes, int clusterPort) {
        var sb = new StringBuilder();

        for (int i = 1;i <= nodes;i++) {
            if (i > 1) {sb.append(",");}
            sb.append("node-").append(i).append(":aether-").append(clusterName).append("-node-").append(i).append(":").append(clusterPort);
        }

        return sb.toString();
    }
}
