package org.pragmatica.aether.cli.cluster;

import org.pragmatica.aether.config.cluster.ClusterManagementConfig;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;


/// Generates per-node `aether.toml` configuration for on-premises deployment.
///
/// Produces a minimal config with node identity, cluster ports, peer list,
/// and TLS settings derived from the cluster management config.
sealed interface NodeConfigTemplate {
    record unused() implements NodeConfigTemplate{}

    static String render(ClusterManagementConfig config,
                         String nodeId,
                         int nodeIndex,
                         String clusterSecret,
                         List<String> allNodeIps) {
        var ports = config.deployment().ports();
        var clusterName = config.cluster().name();
        var tlsEnabled = config.deployment().tls()
                                          .isPresent();
        var peers = buildPeersList(clusterName, allNodeIps, ports.cluster());
        var sb = new StringBuilder();
        sb.append("# Generated by: aether cluster bootstrap\n");
        sb.append("# Node: ").append(nodeId)
                 .append('\n');
        sb.append('\n');
        sb.append("[cluster]\n");
        sb.append("environment = \"docker\"\n");
        sb.append("nodes = ").append(config.cluster().core()
                                                   .count())
                 .append('\n');
        sb.append("tls = ").append(tlsEnabled)
                 .append('\n');
        sb.append('\n');
        sb.append("[cluster.ports]\n");
        sb.append("management = ").append(ports.management())
                 .append('\n');
        sb.append("cluster = ").append(ports.cluster())
                 .append('\n');
        sb.append('\n');
        sb.append("[node]\n");
        sb.append("id = \"").append(nodeId)
                 .append("\"\n");
        sb.append("peers = \"").append(peers)
                 .append("\"\n");
        if (tlsEnabled) {
            sb.append('\n');
            sb.append("[tls]\n");
            sb.append("cluster_secret = \"").append(clusterSecret)
                     .append("\"\n");
        }
        return sb.toString();
    }

    private static String buildPeersList(String clusterName, List<String> nodeIps, int clusterPort) {
        return IntStream.range(0,
                               nodeIps.size()).mapToObj(i -> clusterName + "-" + (i + 1) + ":" + nodeIps.get(i) + ":" + clusterPort)
                              .collect(Collectors.joining(","));
    }
}
