package org.pragmatica.aether.cli.cluster;

import org.pragmatica.aether.config.cluster.ClusterManagementConfig;
import org.pragmatica.aether.config.cluster.RuntimeType;

/// Renders cloud-init user-data scripts for bootstrapping Aether nodes.
///
/// The template generates a bash script that:
/// - Installs Docker if not present (container runtime)
/// - Writes an Aether configuration file
/// - Pulls and runs the Aether node container (or starts JVM)
///
/// Template variables are resolved from the cluster configuration and per-node parameters.
sealed interface UserDataTemplate {
    record unused() implements UserDataTemplate{}

    /// Render a cloud-init script for a single node.
    static String render(ClusterManagementConfig config,
                         String nodeId,
                         int nodeIndex,
                         String clusterSecret,
                         String clusterName) {
        var deployment = config.deployment();
        var cluster = config.cluster();
        var ports = deployment.ports();
        var tlsEnabled = deployment.tls().isPresent();
        var isContainer = deployment.runtime().type() == RuntimeType.CONTAINER;
        var image = deployment.runtime().image()
                                      .or("ghcr.io/pragmaticalabs/aether-node:" + cluster.version());
        var heap = deriveHeap(deployment.instances().getOrDefault("core", "cx21"));
        var sb = new StringBuilder();
        appendHeader(sb, clusterName, nodeId);
        appendVariables(sb,
                        cluster.version(),
                        image,
                        nodeId,
                        clusterSecret,
                        ports.cluster(),
                        ports.management(),
                        ports.swim(),
                        tlsEnabled,
                        cluster.core().count());
        if ( isContainer) {
            appendDockerInstall(sb);
            appendConfig(sb,
                         ports.management(),
                         ports.cluster(),
                         tlsEnabled,
                         clusterSecret,
                         cluster.core().count(),
                         heap);
            appendContainerRun(sb, clusterName, nodeId, ports.cluster(), ports.management(), ports.swim());
        } else

























        {
            appendJvmInstall(sb, cluster.version());
            appendConfig(sb,
                         ports.management(),
                         ports.cluster(),
                         tlsEnabled,
                         clusterSecret,
                         cluster.core().count(),
                         heap);
            appendJvmRun(sb,
                         deployment.runtime().jvmArgs()
                                           .or(""));
        }
        appendReadinessSignal(sb, nodeId, ports.cluster(), ports.management());
        return sb.toString();
    }

    private static void appendHeader(StringBuilder sb, String clusterName, String nodeId) {
        sb.append("#!/bin/bash\n");
        sb.append("set -euo pipefail\n\n");
        sb.append("# --- Aether Node Cloud-Init ---\n");
        sb.append("# Generated by: aether cluster bootstrap\n");
        sb.append("# Cluster: ").append(clusterName)
                 .append('\n');
        sb.append("# Node ID: ").append(nodeId)
                 .append('\n');
        sb.append("# Role: core\n\n");
    }

    private static void appendVariables(StringBuilder sb,
                                        String version,
                                        String image,
                                        String nodeId,
                                        String clusterSecret,
                                        int clusterPort,
                                        int managementPort,
                                        int swimPort,
                                        boolean tlsEnabled,
                                        int coreCount) {
        sb.append("AETHER_VERSION=\"").append(version)
                 .append("\"\n");
        sb.append("AETHER_IMAGE=\"").append(image)
                 .append("\"\n");
        sb.append("AETHER_NODE_ID=\"").append(nodeId)
                 .append("\"\n");
        sb.append("AETHER_CLUSTER_SECRET=\"").append(clusterSecret)
                 .append("\"\n");
        sb.append("AETHER_CLUSTER_PORT=").append(clusterPort)
                 .append('\n');
        sb.append("AETHER_MANAGEMENT_PORT=").append(managementPort)
                 .append('\n');
        sb.append("AETHER_SWIM_PORT=").append(swimPort)
                 .append('\n');
        sb.append("AETHER_TLS_ENABLED=").append(tlsEnabled)
                 .append('\n');
        sb.append("AETHER_CORE_COUNT=").append(coreCount)
                 .append("\n\n");
    }

    private static void appendDockerInstall(StringBuilder sb) {
        sb.append("# --- Install Docker (if not present) ---\n");
        sb.append("if ! command -v docker &> /dev/null; then\n");
        sb.append("    curl -fsSL https://get.docker.com | sh\n");
        sb.append("fi\n\n");
    }

    private static void appendConfig(StringBuilder sb,
                                     int managementPort,
                                     int clusterPort,
                                     boolean tlsEnabled,
                                     String clusterSecret,
                                     int coreCount,
                                     String heap) {
        sb.append("# --- Write Aether config ---\n");
        sb.append("mkdir -p /opt/aether/config\n");
        sb.append("cat > /opt/aether/config/aether.toml <<'AETHER_CONFIG'\n");
        sb.append("[cluster]\n");
        sb.append("environment = \"docker\"\n");
        sb.append("nodes = ").append(coreCount)
                 .append('\n');
        sb.append("tls = ").append(tlsEnabled)
                 .append("\n\n");
        sb.append("[cluster.ports]\n");
        sb.append("management = ").append(managementPort)
                 .append('\n');
        sb.append("cluster = ").append(clusterPort)
                 .append("\n\n");
        sb.append("[node]\n");
        sb.append("heap = \"").append(heap)
                 .append("\"\n");
        sb.append("gc = \"zgc\"\n");
        if ( tlsEnabled) {
            sb.append("\n[tls]\n");
            sb.append("cluster_secret = \"").append(clusterSecret)
                     .append("\"\n");
        }
        sb.append("AETHER_CONFIG\n\n");
    }

    private static void appendContainerRun(StringBuilder sb,
                                           String clusterName,
                                           String nodeId,
                                           int clusterPort,
                                           int managementPort,
                                           int swimPort) {
        sb.append("# --- Pull and run ---\n");
        sb.append("docker pull \"${AETHER_IMAGE}\"\n");
        sb.append("docker run -d \\\n");
        sb.append("    --name aether-node \\\n");
        sb.append("    --restart unless-stopped \\\n");
        sb.append("    --network host \\\n");
        sb.append("    -e AETHER_NODE_ID=\"${AETHER_NODE_ID}\" \\\n");
        sb.append("    -e AETHER_CLUSTER_SECRET=\"${AETHER_CLUSTER_SECRET}\" \\\n");
        sb.append("    -l aether-cluster=").append(clusterName)
                 .append(" \\\n");
        sb.append("    -l aether-node-id=").append(nodeId)
                 .append(" \\\n");
        sb.append("    -l aether-role=core \\\n");
        sb.append("    -v /opt/aether/config:/config:ro \\\n");
        sb.append("    \"${AETHER_IMAGE}\" \\\n");
        sb.append("    --config /config/aether.toml\n\n");
    }

    private static void appendJvmInstall(StringBuilder sb, String version) {
        sb.append("# --- Install Java and Aether ---\n");
        sb.append("if ! command -v java &> /dev/null; then\n");
        sb.append("    apt-get update -qq && apt-get install -y -qq openjdk-21-jre-headless\n");
        sb.append("fi\n");
        sb.append("mkdir -p /opt/aether\n");
        sb.append("curl -fsSL -o /opt/aether/aether-node.jar \\\n");
        sb.append("    \"https://github.com/pragmaticalabs/aether/releases/download/v").append(version)
                 .append("/aether-node.jar\"\n\n");
    }

    private static void appendJvmRun(StringBuilder sb, String jvmArgs) {
        sb.append("# --- Start Aether ---\n");
        sb.append("java ");
        if ( !jvmArgs.isEmpty()) {
        sb.append(jvmArgs).append(' ');}
        sb.append("-jar /opt/aether/aether-node.jar --config /opt/aether/config/aether.toml &\n\n");
    }

    private static void appendReadinessSignal(StringBuilder sb,
                                              String nodeId,
                                              int clusterPort,
                                              int managementPort) {
        sb.append("# --- Signal readiness ---\n");
        sb.append("echo \"Aether node ").append(nodeId)
                 .append(" starting on ports: cluster=")
                 .append(clusterPort)
                 .append(", mgmt=")
                 .append(managementPort)
                 .append("\"\n");
    }

    /// Derive JVM heap from instance type. Simple heuristic based on common cloud sizes.
    private static String deriveHeap(String instanceType) {
        return switch (instanceType) {case "cx11", "t3.small", "e2-small", "Standard_B1s" -> "1g"; case "cx21", "t3.medium", "e2-medium", "Standard_B2s" -> "2g"; case "cx31", "t3.large", "e2-standard-4", "Standard_B4ms" -> "4g"; case "cx41", "t3.xlarge", "e2-standard-8", "Standard_B8ms" -> "8g"; default -> "2g";};
    }
}
