package org.pragmatica.aether.cli.cluster;

import org.pragmatica.aether.config.cluster.ClusterBootstrapConfig;
import org.pragmatica.aether.config.cluster.NodeRole;
import org.pragmatica.aether.config.cluster.RuntimeProfile;
import org.pragmatica.aether.config.cluster.RuntimeType;
import org.pragmatica.aether.config.cluster.SourceProfile;
import org.pragmatica.config.toml.TomlDocument;
import org.pragmatica.config.toml.TomlWriter;
import org.pragmatica.lang.Option;


/// Renders cloud-init user-data scripts for bootstrapping Aether nodes.
///
/// The template generates a bash script that:
/// - Installs Docker if not present (container runtime)
/// - Writes an Aether configuration file
/// - Pulls and runs the Aether node container (or starts JVM)
///
/// Template variables are resolved from the cluster configuration and per-node parameters.
sealed interface UserDataTemplate {
    record unused() implements UserDataTemplate{}

    static String render(ClusterBootstrapConfig config,
                         SourceProfile source,
                         NodeRole role,
                         String nodeId,
                         int nodeIndex,
                         String clusterSecret,
                         String clusterName,
                         TomlDocument composedConfig) {
        var ports = config.operations().ports();
        var runtimeProfile = resolveRuntimeProfile(config, source, role);
        var isContainer = isContainerRuntime(runtimeProfile);
        var image = runtimeProfile.flatMap(RuntimeProfile::image)
                                          .or("ghcr.io/pragmaticalabs/aether-node:" + config.cluster().version());
        var sb = new StringBuilder();
        appendHeader(sb, clusterName, nodeId, role);
        appendVariables(sb,
                        config.cluster().version(),
                        image,
                        nodeId,
                        clusterSecret);
        if (isContainer) {
            appendDockerInstall(sb);
            appendComposedConfig(sb, composedConfig);
            appendContainerRun(sb, clusterName, nodeId);
        } else {
            appendJvmInstall(sb,
                             config.cluster().version());
            appendComposedConfig(sb, composedConfig);
            appendJvmRun(sb,
                         runtimeProfile.flatMap(RuntimeProfile::jvmArgs).or(""));
        }
        appendReadinessSignal(sb, nodeId, ports.cluster(), ports.management());
        return sb.toString();
    }

    private static Option<RuntimeProfile> resolveRuntimeProfile(ClusterBootstrapConfig config,
                                                                SourceProfile source,
                                                                NodeRole role) {
        var roleTable = Option.option(source.roles().get(role));
        return roleTable.map(rt -> rt.runtimeRef()).flatMap(ref -> Option.option(config.runtimes().get(ref)));
    }

    private static boolean isContainerRuntime(Option<RuntimeProfile> profile) {
        return profile.map(p -> p.type() == RuntimeType.CONTAINER || p.type() == RuntimeType.DOCKER || p.type() == RuntimeType.MANAGED_CONTAINER)
                          .or(true);
    }

    private static void appendHeader(StringBuilder sb, String clusterName, String nodeId, NodeRole role) {
        sb.append("#!/bin/bash\n");
        sb.append("set -euo pipefail\n\n");
        sb.append("# --- Aether Node Cloud-Init ---\n");
        sb.append("# Generated by: aether cluster bootstrap\n");
        sb.append("# Cluster: ").append(clusterName)
                 .append('\n');
        sb.append("# Node ID: ").append(nodeId)
                 .append('\n');
        sb.append("# Role: ").append(role.value())
                 .append("\n\n");
    }

    private static void appendVariables(StringBuilder sb,
                                        String version,
                                        String image,
                                        String nodeId,
                                        String clusterSecret) {
        sb.append("AETHER_VERSION=\"").append(version)
                 .append("\"\n");
        sb.append("AETHER_IMAGE=\"").append(image)
                 .append("\"\n");
        sb.append("AETHER_NODE_ID=\"").append(nodeId)
                 .append("\"\n");
        sb.append("AETHER_CLUSTER_SECRET=\"").append(clusterSecret)
                 .append("\"\n\n");
    }

    private static void appendDockerInstall(StringBuilder sb) {
        sb.append("# --- Install Docker (if not present) ---\n");
        sb.append("if ! command -v docker &> /dev/null; then\n");
        sb.append("    curl -fsSL https://get.docker.com | sh\n");
        sb.append("fi\n\n");
    }

    private static void appendComposedConfig(StringBuilder sb, TomlDocument composedConfig) {
        sb.append("# --- Write Aether config (composed: defaults + source-type + operator + CLI overlay) ---\n");
        sb.append("mkdir -p /opt/aether/config\n");
        sb.append("cat > /opt/aether/config/aether.toml <<'AETHER_CONFIG'\n");
        sb.append(TomlWriter.toToml(composedConfig));
        sb.append("AETHER_CONFIG\n\n");
    }

    private static void appendContainerRun(StringBuilder sb, String clusterName, String nodeId) {
        sb.append("# --- Pull and run ---\n");
        sb.append("docker pull \"${AETHER_IMAGE}\"\n");
        sb.append("docker run -d \\\n");
        sb.append("    --name aether-node \\\n");
        sb.append("    --restart unless-stopped \\\n");
        sb.append("    --network host \\\n");
        sb.append("    -l aether-cluster=").append(clusterName)
                 .append(" \\\n");
        sb.append("    -l aether-node-id=").append(nodeId)
                 .append(" \\\n");
        sb.append("    -l aether-role=core \\\n");
        sb.append("    -v /opt/aether/config:/config:ro \\\n");
        sb.append("    \"${AETHER_IMAGE}\" \\\n");
        sb.append("    --config /config/aether.toml\n\n");
    }

    private static void appendJvmInstall(StringBuilder sb, String version) {
        sb.append("# --- Install Java and Aether ---\n");
        sb.append("if ! command -v java &> /dev/null; then\n");
        sb.append("    apt-get update -qq && apt-get install -y -qq openjdk-21-jre-headless\n");
        sb.append("fi\n");
        sb.append("mkdir -p /opt/aether\n");
        sb.append("curl -fsSL -o /opt/aether/aether-node.jar \\\n");
        sb.append("    \"https://github.com/pragmaticalabs/aether/releases/download/v").append(version)
                 .append("/aether-node.jar\"\n\n");
    }

    private static void appendJvmRun(StringBuilder sb, String jvmArgs) {
        sb.append("# --- Start Aether ---\n");
        sb.append("java ");
        if (!jvmArgs.isEmpty()) {sb.append(jvmArgs).append(' ');}
        sb.append("-jar /opt/aether/aether-node.jar --config /opt/aether/config/aether.toml &\n\n");
    }

    private static void appendReadinessSignal(StringBuilder sb, String nodeId, int clusterPort, int managementPort) {
        sb.append("# --- Signal readiness ---\n");
        sb.append("echo \"Aether node ").append(nodeId)
                 .append(" starting on ports: cluster=")
                 .append(clusterPort)
                 .append(", mgmt=")
                 .append(managementPort)
                 .append("\"\n");
    }
}
